# Generated by Django 5.0.6 on 2024-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="news_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
