# Generated by Django 5.1.1 on 2024-09-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        ("projects", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="coauthors",
            field=models.ManyToManyField(
                blank=True, related_name="coauthored_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="conditional",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="questions.conditional",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="curated_last_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="default_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_posts",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="group_of_questions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="questions.groupofquestions",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="notebook",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="posts.notebook",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="postactivityboost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_boosts",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postactivityboost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="postsubscription",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postusersnapshot",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postusersnapshot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="users",
            field=models.ManyToManyField(
                through="posts.PostUserSnapshot", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="postsubscription",
            constraint=models.UniqueConstraint(
                fields=("type", "user_id", "post_id", "is_global"),
                name="postsubscription_unique_type_user_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="postusersnapshot",
            constraint=models.UniqueConstraint(
                fields=("user_id", "post_id"), name="postusersnapshot_unique_user_post"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user_id", "post_id"), name="votes_unique_user_question"
            ),
        ),
    ]
