# Generated by Django 5.1.1 on 2024-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="post",
            name="forecasters_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="post",
            name="vote_score",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
