# Generated by Django 5.1.1 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_comment_count_post_forecasters_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="show_on_homepage",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notebook",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="user_uploaded"),
        ),
    ]
