# Generated by Django 5.0.6 on 2024-07-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_aim_to_close_at_post_scheduled_close_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="closed_at",
            new_name="actual_close_time",
        ),
    ]
