# Generated by Django 5.1.1 on 2024-10-04 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_show_on_homepage_alter_notebook_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="postsubscription",
            name="postsubscription_unique_type_user_post",
        ),
        migrations.AddConstraint(
            model_name="postsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "specific_time"), _negated=True),
                fields=("type", "user_id", "post_id", "is_global"),
                name="postsubscription_unique_type_user_post",
            ),
        ),
    ]
