# Generated by Django 5.0.6 on 2024-06-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_closed_at_post_curation_status_post_rejected_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="curation_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
