# Generated by Django 5.0.6 on 2024-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_postusersnapshot_post_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postusersnapshot",
            name="last_forecast_date",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
