# Generated by Django 5.1.1 on 2024-10-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "posts",
            "0005_remove_postsubscription_postsubscription_unique_type_user_post_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="scheduled_close_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_resolve_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
