# Generated by Django 5.0.6 on 2024-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_curation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="curation_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("closed", "Closed"),
                    ("deleted", "Deleted"),
                    ("resolved", "Resolved"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
