# Generated by Django 5.1.1 on 2024-11-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_scheduled_close_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="open_time",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="actual_close_time",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="resolved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_close_time",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="scheduled_resolve_time",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
