# Generated by Django 5.0.6 on 2024-06-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_curation_status"),
        ("projects", "0010_remove_project_is_public_alter_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="default_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_project",
                to="projects.project",
            ),
        ),
    ]
