# Generated by Django 5.0.6 on 2024-07-09 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_notebook_created_at_alter_notebook_edited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
