# Generated by Django 5.0.6 on 2024-06-25 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_default_project"),
        ("projects", "0010_remove_project_is_public_alter_project_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("markdown", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("news", "News"),
                            ("public_figure", "Public Figure"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="default_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_posts",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="notebook",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="posts.notebook",
            ),
        ),
    ]
