# Generated by Django 5.0.6 on 2024-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_notebook_edited_at_alter_post_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=2000),
        ),
    ]
