# Generated by Django 5.0.6 on 2024-07-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postusersnapshot',
            name='divergence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
