# Generated by Django 5.0.6 on 2024-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_notebook_alter_post_default_project_post_notebook"),
        ("projects", "0013_alter_project_default_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="projects.project"
            ),
        ),
    ]
