# Generated by Django 5.1.1 on 2024-11-13 15:49

from django.db import migrations
from utils.translation import migration_update_default_fields


def migrate(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    Notebook = apps.get_model("posts", "Notebook")
    migration_update_default_fields(Post, ["title", "url_title"])
    migration_update_default_fields(Notebook, ["markdown"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_notebook_content_last_md5_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
