# Generated by Django 5.0.6 on 2024-06-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_notebook_news_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
