# Generated by Django 5.1.1 on 2024-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_populate_original_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="markdown_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_pt",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="url_title_pt",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
    ]
