# Generated by Django 5.0.6 on 2024-06-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_remove_post_rejected_at_and_more"),
        ("posts", "0011_notebook_image_url"),
    ]

    operations = []
