# Generated by Django 5.1.1 on 2024-11-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_notebook_markdown_pt_post_title_pt_post_url_title_pt"),
        ("projects", "0008_project_description_pt_project_name_pt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="default_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_posts",
                to="projects.project",
            ),
        ),
    ]
