# Generated by Django 5.0.6 on 2024-06-29 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_merge_20240628_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 19, 12, 29, 27, 144547, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
