# Generated by Django 5.0.6 on 2024-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_postactivityboost_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url_title",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
