# Generated by Django 5.1.4 on 2025-03-06 17:32
import logging

from django.db import migrations, models
from django.db.models import F

logger = logging.getLogger(__name__)


def migrate(apps, schema_editor):
    Post = apps.get_model("posts", "Post")

    langs = [
        "cs",
        "en",
        "es",
        "original",
        "pt",
        "zh",
    ]

    # Migrate original fields
    Post.objects.update(short_title=F("url_title"))

    for lang in langs:
        Post.objects.update(**{f"short_title_{lang}": f"url_title_{lang}"})
        logger.info(f"Migrated {lang}")


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_alter_post_hotness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="url_title_cs",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_en",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_es",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_original",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_pt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_zh",
        ),
        migrations.AddField(
            model_name="post",
            name="short_title",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_cs",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_en",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_es",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_original",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_pt",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_zh",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="url_title",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=2000
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
