# Generated by Django 5.0.6 on 2024-07-16 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_post_url_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                (
                    "post1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_posts_as_post1",
                        to="posts.post",
                    ),
                ),
                (
                    "post2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_posts_as_post2",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
