# Generated by Django 5.0.6 on 2024-07-25 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_relatedpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cp_change", "Cp Change"),
                            ("new_comments", "New Comments"),
                            ("milestone", "Milestone"),
                            ("status_change", "Status Change"),
                            ("specific_time", "Specific Time"),
                        ],
                        db_index=True,
                    ),
                ),
                ("last_sent_at", models.DateTimeField(db_index=True, null=True)),
                ("next_trigger_value", models.FloatField(db_index=True, null=True)),
                (
                    "next_trigger_datetime",
                    models.DateTimeField(db_index=True, null=True),
                ),
                ("comments_frequency", models.PositiveSmallIntegerField(null=True)),
                ("recurrence_interval", models.DurationField(null=True)),
                ("milestone_step", models.FloatField(null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="postsubscription",
            constraint=models.UniqueConstraint(
                fields=("type", "user_id", "post_id"),
                name="postsubscription_unique_type_user_post",
            ),
        ),
    ]
