# Generated by Django 5.0.6 on 2024-07-19 15:41

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_relatedpost"),
    ]

    operations = [VectorExtension()]
