# Generated by Django 5.1.4 on 2025-03-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0015_post_short_title_post_short_title_cs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="url_title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_cs",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_en",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_es",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_original",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_pt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url_title_zh",
        ),
    ]
