# Generated by Django 5.1.8 on 2025-04-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_remove_post_url_title_remove_post_url_title_cs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="open_time_triggered",
        ),
    ]
