# Generated by Django 5.0.6 on 2024-06-29 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_alter_post_maybe_try_to_resolve_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 19, 12, 54, 14, 570290, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
