# Generated by Django 5.0.6 on 2024-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_postsubscription_cp_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at_triggered",
            field=models.BooleanField(default=False),
        ),
    ]
