# Generated by Django 5.0.6 on 2024-06-30 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_alter_post_maybe_try_to_resolve_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="approved_by",
            new_name="curated_last_by",
        ),
        migrations.RemoveField(
            model_name="post",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="closed_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="resolved_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 20, 23, 47, 32, 39582, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
