# Generated by Django 5.1.7 on 2025-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_remove_post_open_time_triggered"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="markdown_zh_TW",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="short_title_zh_TW",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_zh_TW",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
