# Generated by Django 5.1.8 on 2025-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0018_notebook_markdown_zh_tw_post_short_title_zh_tw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="html_metadata_json",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Custom JSON for HTML meta tags. Supported fields are: title, description, image_url",
                null=True,
            ),
        ),
    ]
