# Generated by Django 5.0.6 on 2024-06-30 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0018_rename_approved_by_post_curated_last_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 20, 23, 48, 27, 808810, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
