# Generated by Django 5.0.6 on 2024-07-30 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0018_post_embedded_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsubscription",
            name="milestone_step",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
