# Generated by Django 5.1.9 on 2025-06-16 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_post_html_metadata_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notebook",
            name="news_type",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="type",
        ),
    ]
