# Generated by Django 5.0.6 on 2024-08-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0019_alter_postsubscription_milestone_step"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelatedPost",
        ),
    ]
