# Generated by Django 5.0.6 on 2024-08-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0020_delete_relatedpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postsubscription",
            old_name="cp_threshold",
            new_name="cp_change_threshold",
        ),
    ]
