# Generated by Django 5.1.10 on 2025-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0020_remove_notebook_news_type_remove_notebook_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
