# Generated by Django 5.0.6 on 2024-06-30 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0020_alter_post_maybe_try_to_resolve_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 20, 23, 53, 42, 689806, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
