# Generated by Django 5.1.9 on 2025-06-25 15:51
from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def migrate_notebook_open_time_triggered(apps, schema_editor):
    Notebook = apps.get_model("posts", "Notebook")

    # TODO: change to 7 days
    # TODO: migration didn't work out :(
    Notebook.objects.filter(
        post__published_at__lte=timezone.now() - timedelta(days=60)
    ).update(open_time_triggered=True)


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_remove_notebook_news_type_remove_notebook_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="open_time_triggered",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.RunPython(
            migrate_notebook_open_time_triggered, migrations.RunPython.noop
        ),
    ]
