# Generated by Django 5.0.6 on 2024-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0021_rename_cp_threshold_postsubscription_cp_change_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="postsubscription",
            name="is_managed_by_user",
            field=models.BooleanField(default=True),
        ),
    ]
