# Generated by Django 5.1.9 on 2025-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0021_notebook_markdown_summary"),
    ]

    operations = [
        # Set all existing records as triggered
        migrations.AddField(
            model_name="notebook",
            name="open_time_triggered",
            field=models.BooleanField(db_index=True, default=True, editable=False),
        ),
        # Bring back default not triggered value for new ones
        migrations.AlterField(
            model_name="notebook",
            name="open_time_triggered",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
