# Generated by Django 5.0.8 on 2024-08-15 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0021_rename_cp_threshold_postsubscription_cp_change_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="postsubscription",
            name="postsubscription_unique_type_user_post",
        ),
        migrations.AddField(
            model_name="postsubscription",
            name="is_global",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name="postsubscription",
            constraint=models.UniqueConstraint(
                fields=("type", "user_id", "post_id", "is_global"),
                name="postsubscription_unique_type_user_post",
            ),
        ),
    ]
