# Generated by Django 5.0.8 on 2024-09-05 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts",
            "0022_remove_postsubscription_postsubscription_unique_type_user_post_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="coauthors",
            field=models.ManyToManyField(
                blank=True, related_name="coauthored_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
