# Generated by Django 5.1.9 on 2025-08-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0022_notebook_open_time_triggered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hotness",
            field=models.FloatField(db_index=True, default=0, editable=False),
        ),
    ]
