# Generated by Django 5.0.8 on 2024-09-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts",
            "0022_remove_postsubscription_postsubscription_unique_type_user_post_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="maybe_try_to_resolve_at",
        ),
    ]
