# Generated by Django 5.1.9 on 2025-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_alter_post_hotness"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_cs",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_original",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_pt",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_zh",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="notebook",
            name="markdown_summary_zh_TW",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
