# Generated by Django 5.0.8 on 2024-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0023_remove_post_maybe_try_to_resolve_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="preview_image_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
