# Generated by Django 5.1.9 on 2025-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0024_notebook_markdown_summary_cs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="actual_resolve_time",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
