# Generated by Django 5.0.8 on 2024-09-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0023_post_coauthors"),
        ("posts", "0025_remove_post_preview_image"),
    ]

    operations = []
