# Generated by Django 5.1.14 on 2025-12-05 15:16
import logging

from django.db import migrations, models
from django.db.models import Subquery, OuterRef

logger = logging.getLogger(__name__)


def migrate_private_comments(apps, schema_editor):
    import logging
    from itertools import groupby

    logger = logging.getLogger(__name__)
    Comment = apps.get_model("comments", "Comment")
    PostUserSnapshot = apps.get_model("posts", "PostUserSnapshot")

    # Get all private comments from non-bot users on posts
    # We assume author__is_bot is available. If not, we might need to fetch User model.
    # To be safe with historical models, we filter by author__is_bot if possible,
    # but if User isn't in the migration state, we might have issues.
    # However, standard Django relations usually allow this lookup.
    comments = (
        Comment.objects.filter(
            is_private=True,
            on_post__isnull=False,
            author__is_bot=False,
        )
        .annotate(
            snapshot_id=Subquery(
                PostUserSnapshot.objects.filter(
                    user_id=OuterRef("author_id"), post_id=OuterRef("on_post_id")
                ).values("id")[:1]
            )
        )
        # .filter(snapshot_id__isnull=False)
        .select_related("author", "on_post")
        .order_by("author_id", "on_post_id", "created_at")
        .only("author_id", "on_post_id", "created_at", "text")
    )

    snapshots = {
        x.id: x
        for x in PostUserSnapshot.objects.filter(
            id__in=[c.snapshot_id for c in comments]
        ).only("id", "private_note", "private_note_updated_at")
    }
    snapshots_to_update = []
    comments_id_delete = []

    for (user_id, post_id), group in groupby(
        comments, key=lambda c: (c.author_id, c.on_post_id)
    ):
        group_comments = list(group)

        note_parts = []
        last_dt = None
        snapshot_id = None

        for comment in group_comments:
            date_str = comment.created_at.strftime("%Y-%m-%d")

            # We have a lot of old auto-generated notes
            # Migrated from the old site reminders, so to avoid making things messy,
            # we keep the comment text without an extra title.
            # Same for cases when user has only one private comment
            # Creation date is visible in the private note section
            if (
                comment.text.startswith("Note imported from date reminder")
                or len(group_comments) == 1
            ):
                note_parts.append(comment.text)
            else:
                note_parts.append(f"### Note from {date_str}\n{comment.text}")

            last_dt = comment.created_at
            snapshot_id = comment.snapshot_id
            comments_id_delete.append(comment.id)

        full_note = "\n\n***\n\n".join(note_parts)

        snapshot = snapshots.get(snapshot_id)

        if not snapshot:
            logger.error(
                f"Comment {[x.id for x in group_comments]} does not have a snapshot id!"
            )

            # Creating a snapshot for such cases
            snapshot = PostUserSnapshot.objects.create(
                user_id=user_id, post_id=post_id, viewed_at=last_dt
            )

        snapshot.private_note = full_note
        snapshot.private_note_updated_at = last_dt

        snapshots_to_update.append(snapshot)

    logger.info(f"Updating {len(snapshots_to_update)} Post Snapshots")
    PostUserSnapshot.objects.bulk_update(
        snapshots_to_update, fields=["private_note", "private_note_updated_at"]
    )

    logger.info(f"Deleting {len(comments_id_delete)} private comments")
    Comment.objects.filter(pk__in=comments_id_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0025_post_actual_resolve_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="postusersnapshot",
            name="private_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postusersnapshot",
            name="private_note_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_private_comments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="postusersnapshot",
            name="private_note_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
