# Generated by Django 5.0.6 on 2024-07-01 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0026_alter_post_maybe_try_to_resolve_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="aim_to_close_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="aim_to_resolve_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 21, 17, 30, 12, 212005, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
