# Generated by Django 5.1.1 on 2024-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_merge_20240906_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_title',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
