# Generated by Django 5.1.15 on 2025-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0026_postusersnapshot_private_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postusersnapshot",
            name="private_note_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
