# Generated by Django 5.0.6 on 2024-07-01 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0027_post_aim_to_close_at_post_aim_to_resolve_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="maybe_try_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2064, 6, 21, 18, 10, 4, 99411, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
