# Generated by Django 5.1.15 on 2026-01-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0027_alter_postusersnapshot_private_note_updated_at"),
        ("questions", "0032_alter_aggregateforecast_forecast_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="questions.question",
            ),
        ),
    ]
