# Generated by Django 5.1.15 on 2026-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0028_alter_post_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_cs",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_en",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_es",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_original",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_pt",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_zh",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="markdown_summary_zh_TW",
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary",
            field=models.TextField(
                blank=True, default="", help_text="Summary text displayed on feed tiles"
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_cs",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_original",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_pt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_zh",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="feed_tile_summary_zh_TW",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary text displayed on feed tiles",
                null=True,
            ),
        ),
    ]
