# Generated by Django 5.1.15 on 2026-03-09 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0029_remove_notebook_markdown_summary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="show_on_homepage",
        ),
    ]
