# Generated by Django 5.2.14 on 2026-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_post_published_at_triggered'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news_hotness',
            field=models.FloatField(db_index=True, default=0, editable=False),
        ),
    ]
