# Generated by Django 5.2.16 on 2026-08-27 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0032_post_news_hotness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="postusersnapshot",
            index=models.Index(
                condition=models.Q(("last_forecast_date__isnull", False)),
                fields=["post", "user"],
                name="posts_postuser_forecasted_idx",
            ),
        ),
    ]
