# Generated by Django 5.2.17 on 2026-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0033_postusersnapshot_posts_postuser_forecasted_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
