# Generated by Django 5.0.6 on 2024-07-09 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_created_at_alter_user_edited_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
