# Generated by Django 5.0.6 on 2024-06-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_bio_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username_change_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
