# Generated by Django 5.1.1 on 2024-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usercampaignregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercampaignregistration",
            name="key",
            field=models.CharField(
                default="-",
                help_text="Key to track the campaign the user registered through.",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
