# Generated by Django 5.0.6 on 2024-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_username_change_date_user_old_usernames"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
