# Generated by Django 5.0.6 on 2024-07-11 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_facebook_user_full_name_user_github_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
