# Generated by Django 5.0.6 on 2024-08-06 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unsubscribed_mailing_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=[],
                size=None,
            ),
        ),
    ]
