# Generated by Django 5.1.4 on 2024-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_level",
            field=models.IntegerField(
                default=0,
                help_text="0: Unverified, 1: Email Verified, "
                "2: Automated Verification, 3: Manual Verification, "
                "4: Verified by direct contact, 5: Is/was moderator, staff, or admin",
            ),
        ),
    ]
