# Generated by Django 5.1.1 on 2024-12-30 11:18

from django.db import migrations


def fw_migration(apps, schema_editor):
    """
    Fix the spelling of 'undegrad' to 'undergrad' in the UserCampaignRegistration details JSON field
    """

    UserCampaignRegistration = apps.get_model("users", "UserCampaignRegistration")

    for registration in UserCampaignRegistration.objects.all():
        details = registration.details
        if "undegrad" in details:
            details["undergrad"] = details.pop("undegrad")
            registration.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_spam"),
    ]

    operations = [
        migrations.RunPython(fw_migration, migrations.RunPython.noop),
    ]
