# Generated by Django 5.1.4 on 2025-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_auto_fix_spelling_campaign_registration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(models.F("is_superuser"), name="is_superuser_idx"),
        ),
    ]
