# Generated by Django 5.1.1 on 2024-09-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0007_alter_user_unsubscribed_mailing_tags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                models.Func("username", function="UPPER"), name="upper_username_idx"
            ),
        ),
    ]
