# Generated by Django 5.1.7 on 2025-03-21 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_is_superuser_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSpamActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("reason", models.TextField()),
                ("confidence", models.FloatField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[("comment", "Comment"), ("post", "Post")],
                        max_length=200,
                    ),
                ),
                ("content_id", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
