# Generated by Django 5.1.7 on 2025-04-08 15:27

from django.db import migrations, models


def update_userspamactivity_content_type(apps, schema_editor):
    UserSpamActivity = apps.get_model("users", "UserSpamActivity")
    Post = apps.get_model("posts", "Post")

    spam_activities = UserSpamActivity.objects.filter(content_type="post")
    for activity in spam_activities:
        if activity.content_id:
            try:
                post = Post.objects.get(id=activity.content_id)

                print(
                    f"\nMigrating Spam activity {activity.id} from post to {'notebook' if post.notebook_id else 'question'}"
                )

                if post.notebook_id is not None:
                    activity.content_type = "notebook"
                    activity.content_id = post.notebook_id
                else:
                    activity.content_type = "question"
                    activity.content_id = post.question_id

                activity.save(update_fields=["content_type", "content_id"])
            except Post.DoesNotExist:
                pass


def reverse_update_userspamactivity_content_type(apps, schema_editor):
    UserSpamActivity = apps.get_model("users", "UserSpamActivity")
    UserSpamActivity.objects.filter(content_type="notebook").update(content_type="post")
    UserSpamActivity.objects.filter(content_type="question").update(content_type="post")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userspamactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userspamactivity",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("question", "Question"),
                    ("notebook", "Notebook"),
                ],
                max_length=200,
            ),
        ),
        migrations.RunPython(
            update_userspamactivity_content_type,
            reverse_update_userspamactivity_content_type,
        ),
    ]
