# Generated by Django 5.1.8 on 2025-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_userspamactivity_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
