# Generated by Django 5.1.10 on 2025-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_prediction_expiration_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="check_for_spam",
            field=models.BooleanField(default=True),
        ),
    ]
