# Generated by Django 5.1.10 on 2025-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_check_for_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="newsletter_optin",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
