# Generated by Django 5.1.9 on 2025-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_check_for_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="app_theme",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="interface_type",
            field=models.CharField(
                choices=[
                    ("consumer_view", "Consumer View"),
                    ("forecaster_view", "Forecaster View"),
                ],
                default="forecaster_view",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("original", "Original content"),
                    ("en", "English"),
                    ("cs", "Czech"),
                    ("es", "Spanish"),
                    ("zh", "Simplified Chinese"),
                    ("zh-TW", "Traditional Chinese"),
                    ("pt", "Portuguese"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
