# Generated by Django 5.1.11 on 2025-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_newsletter_optin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
