# Generated by Django 5.1.10 on 2025-09-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_app_theme_user_interface_type_user_language'),
        ('users', '0013_user_newsletter_optin'),
    ]

    operations = [
    ]
