# Generated by Django 5.1.13 on 2025-10-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_app_theme_user_interface_type_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Optional. This is a field for storing any extra data unique to this user. Structure of this field is not enforced, but should be a dictionary with specific keys. See description in admin panel for an example.",
                null=True,
            ),
        ),
    ]
