# Generated by Django 5.1.13 on 2025-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_access_tier",
            field=models.CharField(
                choices=[
                    ("restricted", "Restricted"),
                    ("unrestricted", "Unrestricted"),
                ],
                default="restricted",
                max_length=32,
                help_text="Indicates the API access tier for the user.",
            ),
        ),
    ]
