# Generated by Django 5.1.15 on 2025-12-15 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_is_primary_bot(apps, schema_editor):
    """
    Migrate existing bot accounts to have `is_primary_bot` set,
    to temporarily give them access to all existing functionality without heavy restrictions.
    After users submit their bot ownership, the `is_primary_bot` flag will be updated based on their preferences.
    """

    User = apps.get_model("users", "User")
    User.objects.filter(is_bot=True).update(is_primary_bot=True)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0015_user_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_primary_bot",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marks the user’s primary bot. Only the primary bot can post public comments, be eligible for prizes, count toward peer scores, and appear on leaderboards.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bot_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The human owner of the bot. This property can only be changed for bot users.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_bot", True), ("bot_owner__isnull", True), _connector="OR"
                ),
                name="user_bot_owner_only_for_bots",
                violation_error_message="Bot owner can be set only for bot account",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_bot", True), ("is_primary_bot", False), _connector="OR"
                ),
                name="user_is_primary_bot_only_for_bots",
                violation_error_message="Is Primary Bot could be set only for bot account",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_bot", True)),
                fields=("bot_owner",),
                name="unique_primary_bot_per_bot_owner",
                violation_error_message="Bot owner could have only one primary bot",
            ),
        ),
        migrations.RunPython(migrate_is_primary_bot, migrations.RunPython.noop),
    ]
