# Generated by Django 5.1.15 on 2026-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_is_primary_bot_user_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_revoked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="All JWT tokens issued before this timestamp are invalid. Set on password change or 'log out everywhere'.",
                null=True,
            ),
        ),
    ]
