# Generated by Django 5.1.15 on 2026-02-15 23:06

from django.db import migrations, models


def migrate(apps, schema_editor):
    # automatically follow on predict should be set to false for existing users
    User = apps.get_model("users", "User")
    User.objects.all().update(automatically_follow_on_predict=False)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_add_auth_revoked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="automatically_follow_on_predict",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="follow_notify_comments_frequency",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="follow_notify_cp_change_threshold",
            field=models.FloatField(
                blank=True,
                default=0.25,
                help_text="Jeffrey's divergence threshold for notifying user of forecasted CP changes.<br>Null means no default.<br>0.05 = small change<br>0.25 = medium change<br>0.6 = large change",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="follow_notify_milestone_step",
            field=models.FloatField(
                blank=True,
                default=0.20,
                help_text="Proportion of question lifetime to trigger notifications",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="follow_notify_on_status_change",
            field=models.BooleanField(default=True),
        ),
    ]
