# Generated by Django 5.2.14 on 2026-05-20 16:46

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_user_automatically_follow_on_predict_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_forecasting_access",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("pending", "Pending"),
                ],
                default="enabled",
                help_text=(
                    "Whether this account may submit forecasts via the API. "
                    "Bots start enabled; human accounts start disabled."
                    "<br>enabled — API forecasts are allowed."
                    "<br>disabled — Blocks API forecasts and hides the in-app banner."
                    "<br>pending — Blocks API forecasts and shows the in-app "
                    "confirmation banner; set automatically on the first blocked "
                    "API forecast."
                ),
                max_length=32,
            ),
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
