# Generated by Django 5.2.14 on 2026-05-20 16:46

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_user_automatically_follow_on_predict_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_forecasting_access",
            field=models.CharField(
                choices=[
                    ("enabled", "Enabled"),
                    ("disabled", "Disabled"),
                    ("pending", "Pending"),
                ],
                default="enabled",
                help_text="Whether this account may submit forecasts via the API. Bots are created as 'enabled'; human accounts default to 'disabled' and move to 'pending' on their first blocked API forecast, which surfaces the in-app confirmation prompt.",
                max_length=32,
            ),
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
