# Generated by Django 5.2.12 on 2026-05-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ("users", "0020_api_forecasting_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exclude_from_aggregations",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "Explicitly excludes this user from aggregations and geometric "
                    "mean for peer scoring, regardless of bot status."
                ),
            ),
        ),
    ]
