# Generated by Django 5.2.16 on 2026-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0023_user_username_set_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                condition=models.Q(("is_staff", True)),
                fields=["id"],
                name="user_is_staff_idx",
            ),
        ),
    ]
