# Generated by Django 5.2.17 on 2026-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_user_user_is_staff_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last applied email change. Starts the change lock and binds the rollback link.",
                null=True,
            ),
        ),
    ]
