# Generated by Django 5.0.6 on 2024-05-25 16:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(db_index=True, null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(db_index=True, null=True)),
                ("resolved_at", models.DateTimeField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("binary", "Binary"),
                            ("numeric", "Numeric Range"),
                            ("date", "Date Range"),
                            ("multiple_choice", "Multiple Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("possibilities", models.JSONField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("_url_id", models.CharField(blank=True, default="", max_length=200)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Begining time when this prediction is active",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Time at which this prediction is no longer active",
                        null=True,
                    ),
                ),
                (
                    "continuous_prediction_values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), null=True, size=202
                    ),
                ),
                ("probability_yes", models.FloatField(null=True)),
                (
                    "probability_yes_per_category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), null=True, size=None
                    ),
                ),
                (
                    "distribution_components",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(null=True),
                        help_text="The components for a continuous prediction. Used to generate prediction_values.",
                        null=True,
                        size=5,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
