# Generated by Django 5.1.1 on 2024-09-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="forecast",
            name="post",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.groupofquestions",
            ),
        ),
        migrations.AddField(
            model_name="forecast",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_forecasts",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="conditional",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditional_conditions",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="conditional",
            name="condition_child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditional_children",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="conditional",
            name="question_no",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditional_no",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="conditional",
            name="question_yes",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditional_yes",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="aggregateforecast",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aggregate_forecasts",
                to="questions.question",
            ),
        ),
    ]
