# Generated by Django 5.0.6 on 2024-07-03 17:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="aim_to_close_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="aim_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
