# Generated by Django 5.0.6 on 2024-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="projects",
            field=models.ManyToManyField(
                related_name="questions", to="projects.project"
            ),
        ),
    ]
