# Generated by Django 5.0.6 on 2024-07-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_groupofquestions_aim_to_close_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="forecasting_open_at",
            new_name="open_time",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="aim_to_close_at",
            new_name="scheduled_close_time",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="aim_to_resolve_at",
            new_name="scheduled_resolve_time",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="resolution_known_at",
            new_name="actual_resolve_time",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="resolution_field_set_at",
            new_name="resolution_set_time",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="closed_at",
            new_name="actual_close_time",
        ),
    ]
