# Generated by Django 5.1.1 on 2024-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aggregateforecast",
            index=models.Index(
                fields=["question", "method", "-start_time"],
                name="questions_a_questio_0d22f0_idx",
            ),
        ),
    ]
