# Generated by Django 5.0.6 on 2024-05-23 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="multiple_choice_options",
            new_name="possibilities",
        ),
        migrations.RemoveField(
            model_name="question",
            name="binary_question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="max",
        ),
        migrations.RemoveField(
            model_name="question",
            name="min",
        ),
        migrations.AddField(
            model_name="question",
            name="_url_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
