# Generated by Django 5.0.6 on 2024-06-05 15:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_projects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="open_lower_bound",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="open_upper_bound",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("binary", "binary"),
                    ("numeric", "numeric"),
                    ("date", "date"),
                    ("multiple_choice", "multiple_choice"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.SmallIntegerField(choices=[(1, "Up"), (-1, "Down")]),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user_id", "question_id"), name="votes_unique_user_question"
            ),
        ),
    ]
