# Generated by Django 5.1.1 on 2024-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_aggregateforecast_questions_a_questio_0d22f0_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "questions_question_post",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW questions_question_post AS
            SELECT q.id,
                   q.id                                                        AS question_id,
                   COALESCE(post_q.id, post_g.id, post_c_yes.id, post_c_no.id) AS post_id
            FROM questions_question q
                     LEFT JOIN posts_post post_q ON q.id = post_q.question_id
                     LEFT JOIN posts_post post_g ON post_g.group_of_questions_id = q.group_id
                     LEFT JOIN questions_conditional c_no ON q.id = c_no.question_no_id
                     LEFT JOIN questions_conditional c_yes ON q.id = c_yes.question_yes_id
                     LEFT JOIN posts_post post_c_no ON post_c_no.conditional_id = c_no.id
                     LEFT JOIN posts_post post_c_yes ON post_c_yes.conditional_id = c_yes.id;
            """,
            "DROP VIEW questions_question_post;",
        ),
    ]
