# Generated by Django 5.0.6 on 2024-06-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0003_question_max_question_min_question_open_lower_bound_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="zero_point",
            field=models.FloatField(null=True),
        ),
    ]
