# Generated by Django 5.0.6 on 2024-05-29 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_vote_vote_votes_unique_user_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="open_lower_bound",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="open_upper_bound",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("binary", "binary"),
                    ("numeric", "numeric"),
                    ("date", "date"),
                    ("multiple_choice", "multiple_choice"),
                ],
                max_length=20,
            ),
        ),
    ]
