# Generated by Django 5.0.6 on 2024-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_rename_forecasting_open_at_question_open_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupofquestions",
            old_name="aim_to_close_at",
            new_name="scheduled_close_time",
        ),
        migrations.RenameField(
            model_name="groupofquestions",
            old_name="aim_to_resolve_at",
            new_name="scheduled_resolve_time",
        ),
    ]
