# Generated by Django 5.0.6 on 2024-05-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_question_approved_at_question_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="approved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="resolved_at",
            field=models.DateTimeField(null=True),
        ),
    ]
