# Generated by Django 5.1.1 on 2024-09-26 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_comment_count_post_forecasters_count_and_more"),
        ("questions", "0004_questionpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aggregateforecast",
            name="questions_a_questio_0d22f0_idx",
        ),
        migrations.AddIndex(
            model_name="aggregateforecast",
            index=models.Index(
                fields=["question", "start_time"], name="questions_a_questio_6aa202_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aggregateforecast",
            index=models.Index(
                fields=["method", "question", "-start_time"],
                name="questions_a_method_2dfe7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["author", "question", "start_time"],
                name="questions_f_author__529ee1_idx",
            ),
        ),
    ]
