# Generated by Django 5.0.6 on 2024-07-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0004_rename_aim_to_close_at_groupofquestions_scheduled_close_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupofquestions",
            old_name="label",
            new_name="group_variable",
        ),
        migrations.RemoveField(
            model_name="groupofquestions",
            name="scheduled_close_time",
        ),
        migrations.RemoveField(
            model_name="groupofquestions",
            name="scheduled_resolve_time",
        ),
    ]
