# Generated by Django 5.0.6 on 2024-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_rename_continuous_prediction_values_forecast_cdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("binary", "Binary"),
                    ("numeric", "Numeric"),
                    ("date", "Date"),
                    ("multiple_choice", "Multiple Choice"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="direction",
            field=models.SmallIntegerField(),
        ),
    ]
