# Generated by Django 5.1.1 on 2024-09-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questions",
            "0005_remove_aggregateforecast_questions_a_questio_0d22f0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="open_time",
            field=models.DateTimeField(db_index=True),
        ),
    ]
