# Generated by Django 5.0.6 on 2024-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_rename_label_groupofquestions_group_variable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="fine_print",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="resolution_criteria_description",
            field=models.TextField(blank=True, default=" "),
            preserve_default=False,
        ),
    ]
