# Generated by Django 5.0.6 on 2024-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_question_fine_print_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="cp_reveal_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
