# Generated by Django 5.0.6 on 2024-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_type_alter_vote_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')]),
        ),
    ]
