# Generated by Django 5.0.6 on 2024-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_question__url_id_remove_question_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('resolved', 'Resolved'), ('ambiguous', 'Ambiguous'), ('annulled', 'Annulled'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
