# Generated by Django 5.0.6 on 2024-06-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0008_remove_question__url_id_remove_question_approved_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupOfQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Conditional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditional_parents",
                        to="questions.question",
                    ),
                ),
                (
                    "condition_child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditional_children",
                        to="questions.question",
                    ),
                ),
                (
                    "question_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditional_no",
                        to="questions.question",
                    ),
                ),
                (
                    "question_yes",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditional_yes",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="question",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.groupofquestions",
            ),
        ),
    ]
