# Generated by Django 5.1.1 on 2024-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_alter_question_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="description_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="description_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="description_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_original",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_zh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_cs",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_en",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_es",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_original",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_zh",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
