# Generated by Django 5.0.6 on 2024-07-09 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_alter_conditional_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditional",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupofquestions",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
