# Generated by Django 5.1.1 on 2024-11-13 15:49

from django.db import migrations
from utils.translation import migration_update_default_fields


def migrate(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    GroupOfQuestions = apps.get_model("questions", "GroupOfQuestions")
    migration_update_default_fields(
        Question, ["description", "resolution_criteria", "fine_print", "label", "title"]
    )
    migration_update_default_fields(
        GroupOfQuestions, ["description", "resolution_criteria", "fine_print"]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_groupofquestions_content_last_md5_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
