# Generated by Django 5.0.6 on 2024-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_conditional"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conditional",
            old_name="condition_parent",
            new_name="condition",
        ),
    ]
