# Generated by Django 5.0.6 on 2024-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_alter_conditional_edited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=2000),
        ),
    ]
