# Generated by Django 5.0.6 on 2024-06-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_groupofquestions_conditional_question_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="slider_values",
            field=models.JSONField(null=True),
        ),
    ]
