# Generated by Django 5.0.6 on 2024-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_forecast_slider_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="closed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_lower_bound",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_upper_bound",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="zero_point",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
