# Generated by Django 5.1.1 on 2024-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_populate_original_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_pt",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
