# Generated by Django 5.0.6 on 2024-07-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_post_forecasts_count_vote_created_at_vote_edited_at"),
        ("questions", "0010_alter_question_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="post",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="posts.post",
            ),
        ),
    ]
