# Generated by Django 5.0.6 on 2024-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_forecast_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="composed_forecasts",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
