# Generated by Django 5.1.1 on 2024-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0011_groupofquestions_description_pt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="group_variable",
            field=models.CharField(blank=True),
        ),
    ]
