# Generated by Django 5.0.6 on 2024-06-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_alter_question_closed_at_alter_question_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="closed_at",
        ),
    ]
