# Generated by Django 5.1.1 on 2024-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0012_question_group_variable"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("api", "Api"), ("ui", "Ui"), ("automatic", "Automatic")],
                default="",
                max_length=30,
                null=True,
            ),
        ),
    ]
