# Generated by Django 5.0.6 on 2024-06-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0012_alter_question_closed_at_alter_question_resolved_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="closed_at",
        ),
    ]
