# Generated by Django 5.0.6 on 2024-06-30 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0013_remove_question_closed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="resolved_at",
        ),
        migrations.AddField(
            model_name="question",
            name="aim_to_close_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2051, 11, 16, 23, 47, 32, 35209, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="aim_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2051, 11, 16, 23, 47, 32, 35567, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="closed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="forecasting_open_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_field_set_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_known_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
