# Generated by Django 5.1.4 on 2024-12-30 19:23

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0013_forecast_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="cdf_size",
            field=models.IntegerField(
                blank=True,
                help_text="Number of values required in a submitted CDF. Determines the number of possible outcomes this question may take (cdf_size-1).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="continuous_cdf",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.FloatField(), max_length=201, null=True, size=None
            ),
        ),
    ]
