# Generated by Django 5.0.8 on 2024-08-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0013_rename_max_question_range_max_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupofquestions",
            old_name="resolution_criteria_description",
            new_name="resolution_criteria",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="resolution_criteria_description",
            new_name="resolution_criteria",
        ),
    ]
