# Generated by Django 5.0.8 on 2024-08-15 17:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_rename_resolution_criteria_description_groupofquestions_resolution_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('recency_weighted', 'Recency Weighted'), ('unweighted', 'Unweighted'), ('single_aggregation', 'Single Aggregation')], max_length=200)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True, null=True)),
                ('forecast_values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), max_length=201, size=None)),
                ('forecaster_count', models.IntegerField(null=True)),
                ('interval_lower_bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('centers', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('interval_upper_bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('means', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('histogram', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_forecasts', to='questions.question')),
            ],
        ),
    ]
