# Generated by Django 5.1.4 on 2025-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0015_remove_forecast_distribution_components_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="is_automatically_translated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="is_automatically_translated",
            field=models.BooleanField(default=True),
        ),
    ]
