# Generated by Django 5.0.8 on 2024-08-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0015_aggregateforecast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_forecasts",
                to="questions.question",
            ),
        ),
    ]
