# Generated by Django 5.0.8 on 2024-08-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_forecast_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateforecast',
            name='method',
            field=models.CharField(choices=[('recency_weighted', 'Recency Weighted'), ('unweighted', 'Unweighted'), ('single_aggregation', 'Single Aggregation'), ('metaculus_prediction', 'Metaculus Prediction')], max_length=200),
        ),
    ]
