# Generated by Django 5.1.4 on 2025-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0016_groupofquestions_is_automatically_translated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="unit",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
