# Generated by Django 5.1.5 on 2025-03-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0016_groupofquestions_is_automatically_translated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="actual_close_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when the question actually closed.\n        This is the minimum of scheduled_close_time and actual_resolve_time once\n        the resolution is known.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="actual_resolve_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when the resolution actually became known.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="cp_reveal_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the community prediction is revealed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when this question opens for forecasting.\n        Defines the beginning of the forecasting period used in scoring. Do not change\n        after forecasts have been made.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="resolution_set_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when the resolution was set.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="scheduled_close_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when this question closes for forecasting.\n        Defines the end of the forecasting period used in scoring. Do not change\n        after forecasts have been made.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="scheduled_resolve_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when it is predicted that the resolution will become known.",
                null=True,
            ),
        ),
    ]
