# Generated by Django 5.0.6 on 2024-06-30 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0016_alter_question_aim_to_close_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="aim_to_close_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2051, 11, 16, 23, 53, 42, 688418, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="aim_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2051, 11, 16, 23, 53, 42, 688527, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
