# Generated by Django 5.1.7 on 2025-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_question_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="subquestions_order",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CP_ASC", "Cp Asc"),
                    ("CP_DESC", "Cp Desc"),
                ],
                default=None,
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="group_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
