# Generated by Django 5.0.8 on 2024-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_alter_aggregateforecast_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="graph_type",
            field=models.CharField(
                choices=[
                    ("fan_graph", "Fan Graph"),
                    ("multiple_choice_graph", "Multiple Choice Graph"),
                ],
                default="multiple_choice_graph",
                max_length=256,
            ),
        ),
    ]
