# Generated by Django 5.1.7 on 2025-03-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_alter_question_actual_close_time_and_more"),
        ("questions", "0018_groupofquestions_subquestions_order_and_more"),
    ]

    operations = []
