# Generated by Django 5.0.8 on 2024-08-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0018_groupofquestions_graph_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="forecast_scoring_ends",
        ),
    ]
