# Generated by Django 5.0.8 on 2024-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_remove_question_forecast_scoring_ends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='composed_forecasts',
        ),
        migrations.AddField(
            model_name='question',
            name='include_bots_in_aggregations',
            field=models.BooleanField(default=False),
        ),
    ]
