# Generated by Django 5.1.7 on 2025-03-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0019_merge_20250319_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="spot_scoring_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when spot scores are evaluated.\n        If not set, defaults to spot_scoring time.",
                null=True,
            ),
        ),
    ]
