# Generated by Django 5.1.7 on 2025-03-23 20:00

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


def reverse_migrate(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(type="discrete").update(type="numeric")


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0020_question_spot_scoring_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="inbound_outcome_count",
            field=models.IntegerField(
                blank=True,
                help_text="For Discrete only.\n        Number of possible outcomes NOT including out of bounds values.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="continuous_cdf",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.FloatField(),
                max_length=201,
                null=True,
                size=None,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_lower_bound",
            field=models.BooleanField(
                blank=True,
                help_text="For Continuous only.\n        If there can be a resolution below the range_min.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_upper_bound",
            field=models.BooleanField(
                blank=True,
                help_text="For Continuous only.\n        If there can be a resolution above the range_max.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="range_max",
            field=models.FloatField(
                blank=True,
                help_text="For Continuous only.\n        Maximum inbound value. For Discrete, this is 1/2 a unit's width above the\n        displayed upper bound.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="range_min",
            field=models.FloatField(
                blank=True,
                help_text="For Continuous only.\n        Minimum inbound value. For Discrete, this is 1/2 a unit's width below the\n        displayed lower bound.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="spot_scoring_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when spot scores are evaluated.\n        If not set, defaults to cp reveal time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("binary", "Binary"),
                    ("multiple_choice", "Multiple Choice"),
                    ("numeric", "Numeric"),
                    ("date", "Date"),
                    ("discrete", "Discrete"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="zero_point",
            field=models.FloatField(
                blank=True,
                help_text="For Continuous only. NOT for Discrete.\n        If logarithmically scaled, the value of the zero point.",
                null=True,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_migrate),
    ]
