# Generated by Django 5.1.7 on 2025-03-22 16:55

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


def migrate(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(
        inbound_outcome_count__isnull=True,
        type__in=["date", "numeric"],
    ).update(inbound_outcome_count=200)


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0020_question_spot_scoring_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="inbound_outcome_count",
            field=models.IntegerField(
                blank=True,
                help_text="For Continuous only.\n        Number of possible outcomes NOT including out of bounds values.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="continuous_cdf",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.FloatField(), max_length=201, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_lower_bound",
            field=models.BooleanField(
                blank=True,
                help_text="For Continuous only.\n        If there can be a resolution below the range_min.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="open_upper_bound",
            field=models.BooleanField(
                blank=True,
                help_text="For Continuous only.\n        If there can be a resolution above the range_max.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="range_max",
            field=models.FloatField(
                blank=True,
                help_text="For Continuous only.\n        Maximum inbound value.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="range_min",
            field=models.FloatField(
                blank=True,
                help_text="For Continuous only.\n        Minimum inbound value.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="zero_point",
            field=models.FloatField(
                blank=True,
                help_text="For Continuous only.\n        If logaritmically scaled, the value of the zero point.",
                null=True,
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
