# Generated by Django 5.1.8 on 2025-04-10 14:49

from django.db import migrations, models
from django.utils import timezone


def migrate(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(open_time__lt=timezone.now()).update(
        open_time_triggered=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0021_question_inbound_outcome_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="open_time_triggered",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
