# Generated by Django 5.0.6 on 2024-07-01 17:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0022_alter_question_aim_to_close_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="forecast_scoring_ends",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="conditional",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditional_conditions",
                to="questions.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="aim_to_close_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2051, 11, 17, 17, 18, 38, 761886, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="aim_to_resolve_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2051, 11, 17, 17, 18, 38, 761996, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
