# Generated by Django 5.1.8 on 2025-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0022_question_open_time_triggered"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="movement",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
