# Generated by Django 5.1.7 on 2025-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0023_question_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofquestions",
            name="description_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="fine_print_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupofquestions",
            name="resolution_criteria_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fine_print_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="label_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="resolution_criteria_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="title_zh_TW",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
