# Generated by Django 5.1.9 on 2025-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0024_groupofquestions_description_zh_tw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupofquestions",
            name="subquestions_order",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CP_ASC", "Cp Asc"),
                    ("CP_DESC", "Cp Desc"),
                ],
                default="CP_DESC",
                max_length=12,
            ),
        ),
    ]
