# Generated by Django 5.1.9 on 2025-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0026_userforecastnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="default_score_type",
            field=models.CharField(
                choices=[
                    ("relative_legacy", "Relative Legacy"),
                    ("peer", "Peer"),
                    ("baseline", "Baseline"),
                    ("spot_peer", "Spot Peer"),
                    ("spot_baseline", "Spot Baseline"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="peer",
                help_text='Default score type for this question.\n        Generally, this should be either "peer" or "spot_peer".\n        Determines which score will be most prominently displayed in the UI.\n        Also, for Leaderboards that have a "score type" of "default", this question\'s\n        default score type will be the one that contributes to the leaderboard.\n        ',
                max_length=20,
            ),
        ),
    ]
