# Generated by Django 5.1.9 on 2025-07-01 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_remove_notebook_news_type_remove_notebook_type"),
        ("questions", "0027_question_default_score_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True),
                    ("end_time__gt", models.F("start_time")),
                    _connector="OR",
                ),
                name="end_time_after_start_time",
            ),
        ),
    ]
