# Generated by Django 5.1.11 on 2025-08-07 20:06

from django.db import migrations, models


def migrate(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    for question in Question.objects.filter(default_score_type__startswith="spot"):
        question.default_aggregation_method = "unweighted"
        question.save(update_fields=["default_aggregation_method"])


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0028_forecast_end_time_after_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="default_aggregation_method",
            field=models.CharField(
                choices=[
                    ("recency_weighted", "Recency Weighted"),
                    ("unweighted", "Unweighted"),
                    ("single_aggregation", "Single Aggregation"),
                    ("metaculus_prediction", "Metaculus Prediction"),
                ],
                db_index=True,
                default="recency_weighted",
                help_text='Default aggregation method for this question.\n        Determines which aggregation is calculated and presented for this question.\n        <br>This should generally be either "recency_weighted", but for very short-term\n        questions, or ones where forecasting is done live, "unweighted" is likely\n        a better choice.\n        ',
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
