# Generated by Django 5.1.10 on 2025-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0029_question_default_aggregation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="include_bots_in_aggregates",
            field=models.BooleanField(default=True),
        ),
    ]
