# Generated by Django 5.1.10 on 2025-10-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0029_question_default_aggregation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="cp_reveal_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Time when the community prediction is revealed.",
                null=True,
            ),
        ),
    ]
