# Generated by Django 5.1.9 on 2025-09-09 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0029_question_default_aggregation_method"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW questions_question_post AS
            SELECT q.id as id, q.id AS question_id, p.id AS post_id
            FROM posts_post p
                     JOIN questions_question q ON q.id = p.question_id
            UNION
            SELECT q.id, q.id, p.id
            FROM posts_post p
                     JOIN questions_question q ON q.group_id = p.group_of_questions_id
            UNION
            SELECT c.question_yes_id, c.question_yes_id, p.id
            FROM posts_post p
                     JOIN questions_conditional c ON p.conditional_id = c.id
            UNION
            SELECT c.question_no_id, c.question_no_id, p.id
            FROM posts_post p
                     JOIN questions_conditional c ON p.conditional_id = c.id;
            """,
            """
            CREATE OR REPLACE VIEW questions_question_post AS
            SELECT q.id,
                   q.id                                                        AS question_id,
                   COALESCE(post_q.id, post_g.id, post_c_yes.id, post_c_no.id) AS post_id
            FROM questions_question q
                     LEFT JOIN posts_post post_q ON q.id = post_q.question_id
                     LEFT JOIN posts_post post_g ON post_g.group_of_questions_id = q.group_id
                     LEFT JOIN questions_conditional c_no ON q.id = c_no.question_no_id
                     LEFT JOIN questions_conditional c_yes ON q.id = c_yes.question_yes_id
                     LEFT JOIN posts_post post_c_no ON post_c_no.conditional_id = c_no.id
                     LEFT JOIN posts_post post_c_yes ON post_c_yes.conditional_id = c_yes.id;
            """
        ),
    ]
