# Generated by Django 5.1.14 on 2025-11-10 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0025_post_actual_resolve_time"),
        ("questions", "0030_alter_question_cp_reveal_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["author", "post", "question"],
                name="questions_f_author__d4ea27_idx",
            ),
        ),
    ]
