# Generated by Django 5.1.13 on 2025-11-28 18:17

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0031_forecast_questions_f_author__d4ea27_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregateforecast",
            name="forecast_values",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.FloatField(null=True), max_length=201, size=None
            ),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="probability_yes_per_category",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.FloatField(null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
