# Generated by Django 5.1.13 on 2025-11-15 19:35
from datetime import datetime


import questions.models
from django.db import migrations, models


def initialize_options_history(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    questions = Question.objects.filter(options__isnull=False)
    for question in questions:
        if question.options:
            question.options_history = [(datetime.min.isoformat(), question.options)]
    Question.objects.bulk_update(questions, ["options_history"])


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0032_alter_aggregateforecast_forecast_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("api", "Api"), ("ui", "Ui"), ("automatic", "Automatic")],
                db_index=True,
                default="",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="options_history",
            field=models.JSONField(
                blank=True,
                help_text="For Multiple Choice only.\n        <br>list of tuples: (isoformat_datetime, options_list). (json stores them as lists)\n        <br>Records the history of options over time.\n        <br>Initialized with (datetime.min.isoformat(), self.options) upon question creation.\n        <br>Updated whenever options are changed.",
                null=True,
                validators=[questions.models.validate_options_history],
            ),
        ),
        migrations.RunPython(
            initialize_options_history, reverse_code=migrations.RunPython.noop
        ),
    ]
