# Generated by Django 5.1.10 on 2026-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0034_question_status_filter_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="cp_reveal_time_triggered",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
            ),
        ),
    ]
