# Generated by Django 5.1.15 on 2026-02-05 18:42

from django.db import migrations, models
from django.utils import timezone


def set_already_revealed(apps, schema_editor):
    # Mark already-revealed questions as triggered to avoid tons of outdated CP reveal notifications
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(cp_reveal_time__lte=timezone.now()).update(
        cp_reveal_time_triggered=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0035_question_options_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="cp_reveal_time_triggered",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.RunPython(set_already_revealed, migrations.RunPython.noop),
    ]
