# Generated by Django 5.1.15 on 2026-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0036_question_cp_reveal_time_triggered"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="options_order",
            field=models.CharField(
                choices=[("DEFAULT", "Default"), ("CP_DESC", "Cp Desc")],
                default="DEFAULT",
                help_text="For Multiple Choice only.\n        DEFAULT: current default behavior (display views sort by CP, forecast maker preserves creation order).\n        CP_DESC: all views sort options by descending community prediction.",
                max_length=12,
            ),
        ),
    ]
