# Generated by Django 5.2.14 on 2026-06-18 15:18

from django.db import migrations, models
from django.utils import timezone

from questions.serializers.aggregate_forecasts import serialize_aggregate_forecast


def migrate(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    now = timezone.now()
    for question in Question.objects.filter(
        actual_close_time__isnull=True,
        open_time__lte=now,
    ):
        latest = (
            question.aggregate_forecasts.filter(start_time__lte=now)
            .order_by("-start_time")
            .first()
        )
        question.latest_aggregate_forecast = (
            None
            if latest is None
            else serialize_aggregate_forecast(latest, question.type, full=True)
        )
        question.save(update_fields=["latest_aggregate_forecast"])


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0037_question_options_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="latest_aggregate_forecast",
            field=models.JSONField(
                blank=True,
                help_text="Serialized form of the latest aggregate forecast for this question.",
                null=True,
            ),
        ),
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop),
    ]
