# Generated by Django 5.2.14 on 2026-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_question_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label_color',
            field=models.CharField(blank=True, help_text="Admin-set frontend palette key ('1'..'18') overriding the index-based subquestion color.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options_colors',
            field=models.JSONField(blank=True, help_text="For Multiple Choice only.\n        Dict of option label -> frontend palette key ('1'..'18').\n        Overrides the default index-based option color.", null=True),
        ),
    ]
