# Generated by Django 5.2.14 on 2026-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0031_post_published_at_triggered"),
        ("questions", "0037_question_options_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["id"],
                include=("default_aggregation_method",),
                name="idx_q_id_incl_default_agg",
            ),
        ),
    ]
