version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bun"
    directory: "/front_end"
    schedule:
      interval: "daily"