# Generated by Django 5.0.6 on 2024-05-24 20:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TOURNAMENT", "Tournament"),
                            ("CATEGORY", "Category"),
                            ("TAG", "Tag"),
                            ("TOPIC", "Topic"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[-a-zA-Z0-9_]*[a-zA-Z][-a-zA-Z0-9_]*\\Z",
                                "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens. Must contain at least one letter.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                ("subtitle", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("header_image", models.CharField(blank=True, null=True)),
                ("header_logo", models.CharField(blank=True, null=True)),
                ("emoji", models.CharField(default="", max_length=10)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Will be displayed ordered by this field inside each section",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Public projects are accessible to all users even if they're not project members.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive projects are not accessible to all users",
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=15, null=True
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("close_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sign_up_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Used during tournament onboarding.",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hot_topics", "Hot Topics section"),
                            ("hot_categories", "Hot Categories section"),
                        ],
                        default=None,
                        help_text="This groups topics together under the same section in the sidebar. ",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("meta_description", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("type", "slug"), name="projects_unique_type_slug"
            ),
        ),
    ]
