# Generated by Django 5.0.6 on 2024-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("tournament", "Tournament"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("topic", "Topic"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
