<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-27 21:53
=======
# Generated by Django 5.0.6 on 2024-05-27 21:44
>>>>>>> 4581e32bf032564bd038bfe61cb3496219a0ffef

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD

=======
>>>>>>> 4581e32bf032564bd038bfe61cb3496219a0ffef
    dependencies = [
        ("projects", "0002_alter_project_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("order",)},
        ),
    ]
