# Generated by Django 5.0.6 on 2024-05-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("order",)},
        ),
    ]
