# Generated by Django 5.1.1 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="show_on_homepage",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
