# Generated by Django 5.0.6 on 2024-05-28 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[-a-zA-Z0-9_]*[a-zA-Z][-a-zA-Z0-9_]*\\Z",
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens. Must contain at least one letter.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
