# Generated by Django 5.0.6 on 2024-07-09 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_created_at_alter_project_edited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectuserpermission",
            name="edited_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
