# Generated by Django 5.0.6 on 2024-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("tournament", "Tournament"),
                    ("question_series", "Question Series"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("topic", "Topic"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
