# Generated by Django 5.0.6 on 2024-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hot_topics", "Hot Topics"),
                    ("hot_categories", "Hot Categories"),
                ],
                default=None,
                help_text="This groups topics together under the same section in the sidebar. ",
                max_length=32,
                null=True,
            ),
        ),
    ]
