# Generated by Django 5.0.6 on 2024-06-13 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_permission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("viewer", "Viewer"),
                    ("forecaster", "Forecaster"),
                    ("curator", "Curator"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="forecaster",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProjectUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("forecaster", "Forecaster"),
                            ("curator", "Curator"),
                            ("admin", "Admin"),
                        ]
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="override_permissions",
            field=models.ManyToManyField(
                through="projects.ProjectUserPermission", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="projectuserpermission",
            constraint=models.UniqueConstraint(
                fields=("user_id", "project_id"),
                name="projectuserpermission_unique_user_id_project_id",
            ),
        ),
    ]
