# Generated by Django 5.0.6 on 2024-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_default_permission_projectuserpermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("tournament", "Tournament"),
                    ("question_series", "Question Series"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("topic", "Topic"),
                    ("personal_list", "Personal List"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
