# Generated by Django 5.1.1 on 2024-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_populate_original_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_pt",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name_pt",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_pt",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
