# Generated by Django 5.0.6 on 2024-06-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectuserpermission",
            name="permission",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer"),
                    ("forecaster", "Forecaster"),
                    ("curator", "Curator"),
                    ("admin", "Admin"),
                ],
                db_index=True,
            ),
        ),
    ]
