# Generated by Django 5.1.4 on 2024-12-13 14:09

from django.db import migrations, models
from django.db.models import When, Case, Value, Q


def migrate(apps, schema_editor):
    """
    We assume that all existing users with an activated email have completed onboarding.
    """

    Project = apps.get_model("projects", "Project")
    Project.objects.update(
        visibility=Case(
            # If the post is unlisted, set visibility to UNLISTED
            When(unlisted=True, then=Value("unlisted")),
            # If add_posts_to_main_feed is True and is not private,
            # set visibility to NORMAL
            When(
                Q(add_posts_to_main_feed=True) & Q(default_permission__isnull=False),
                then=Value("normal"),
            ),
            # Otherwise, set visibility to NOT_IN_MAIN_FEED
            default=Value("not_in_main_feed"),
            output_field=models.CharField(),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_project_description_pt_project_name_pt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("not_in_main_feed", "Not In Main Feed"),
                    ("unlisted", "Unlisted"),
                ],
                db_index=True,
                default="not_in_main_feed",
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
