# Generated by Django 5.0.6 on 2024-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectuserpermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leaderboard_type',
            field=models.CharField(choices=[('relative_legacy', 'Relative Legacy'), ('peer', 'Peer'), ('baseline', 'Baseline'), ('spot_peer', 'Spot Peer'), ('spot_baseline', 'Spot Baseline'), ('comment_insight', 'Comment Insight'), ('question_writing', 'Question Writing')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('global_leaderboard', 'Global Leaderboard'), ('question_series', 'Question Series'), ('category', 'Category'), ('tag', 'Tag'), ('topic', 'Topic'), ('personal_list', 'Personal List')], db_index=True, max_length=32),
        ),
    ]
