# Generated by Django 5.1.4 on 2024-12-16 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_project_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="add_posts_to_main_feed",
        ),
        migrations.RemoveField(
            model_name="project",
            name="unlisted",
        ),
    ]
