# Generated by Django 5.0.6 on 2024-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_project_is_public_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default_permission',
            field=models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('forecaster', 'Forecaster'), ('curator', 'Curator'), ('admin', 'Admin'), ('none', 'None')], db_index=True, default='forecaster', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='prize_pool',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectuserpermission',
            name='permission',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('forecaster', 'Forecaster'), ('curator', 'Curator'), ('admin', 'Admin'), ('none', 'None')], db_index=True),
        ),
    ]
