# Generated by Django 5.1.4 on 2025-02-25 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_project_add_posts_to_main_feed_and_more"),
        ("questions", "0015_remove_forecast_distribution_components_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("site_main", "Site Main"),
                    ("index", "Index"),
                    ("tournament", "Tournament"),
                    ("question_series", "Question Series"),
                    ("personal_project", "Personal Project"),
                    ("news_category", "News Category"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("topic", "Topic"),
                    ("community", "Community"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProjectIndexQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("weight", models.FloatField()),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Will be displayed ordered by this field inside each section",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_questions",
                        to="projects.project",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Index Post Question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "question"),
                        name="projectindexquestion_unique_project_question",
                    )
                ],
            },
        ),
    ]
