# Generated by Django 5.0.6 on 2024-06-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_leaderboard_type_alter_project_type'),
        ('projects', '0010_remove_project_is_public_alter_project_type'),
    ]

    operations = [
    ]
