# Generated by Django 5.0.6 on 2024-06-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_merge_20240623_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('site_main', 'Site Main'), ('tournament', 'Tournament'), ('global_leaderboard', 'Global Leaderboard'), ('question_series', 'Question Series'), ('personal_project', 'Personal Project'), ('category', 'Category'), ('tag', 'Tag'), ('topic', 'Topic')], db_index=True, max_length=32),
        ),
    ]
