# Generated by Django 5.1.4 on 2025-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_project_type_projectindexquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_automatically_translated",
            field=models.BooleanField(default=True),
        ),
    ]
