# Generated by Django 5.1.8 on 2025-04-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_project_is_automatically_translated"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="forecasting_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
