# Generated by Django 5.0.6 on 2024-06-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_project_default_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("site_main", "Site Main"),
                    ("tournament", "Tournament"),
                    ("global_leaderboard", "Global Leaderboard"),
                    ("question_series", "Question Series"),
                    ("personal_project", "Personal Project"),
                    ("news_category", "News Category"),
                    ("public_figure", "Public Figure"),
                    ("category", "Category"),
                    ("tag", "Tag"),
                    ("topic", "Topic"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
