# Generated by Django 5.1.7 on 2025-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_project_forecasting_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_zh_TW",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name_zh_TW",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle_zh_TW",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
