# Generated by Django 5.1.8 on 2025-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_project_description_zh_tw_project_name_zh_tw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="forecasts_flow_enabled",
            field=models.BooleanField(
                default=False, help_text="Enables new forecast flow for tournaments"
            ),
        ),
    ]
