# Generated by Django 5.1.7 on 2025-05-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_forecasts_flow_enabled"),
        ("projects", "0015_remove_project_include_bots_in_leaderboard_and_more"),
    ]

    operations = []
