# Generated by Django 5.1.7 on 2025-05-08 16:04

from django.db import migrations, models


def migrate(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(include_bots_in_leaderboard=True).update(
        bot_leaderboard_status="include"
    )
    Project.objects.filter(include_bots_in_leaderboard=False).update(
        bot_leaderboard_status="exclude_and_show"
    )


def reverse_migrate(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(bot_leaderboard_status__in=["include", "bots_only"]).update(
        include_bots_in_leaderboard=True
    )
    Project.objects.filter(
        bot_leaderboard_status__in=["exclude_and_hide", "exclude_and_show"]
    ).update(include_bots_in_leaderboard=False)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_forecasts_flow_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bot_leaderboard_status",
            field=models.CharField(
                choices=[
                    ("exclude_and_hide", "Exclude And Hide"),
                    ("exclude_and_show", "Exclude And Show"),
                    ("include", "Include"),
                    ("bots_only", "Bots Only"),
                ],
                default="exclude_and_show",
                help_text="Sets the status of bots in any leaderboard associated with this project.<br>\n        exclude_and_hide: Bots are excluded from ranks/prizes/medals and hidden from the leaderboard.<br>\n        exclude_and_show: Bots are excluded from ranks/prizes/medals but shown on the leaderboard.<br>\n        include: Bots are included in ranks/prizes/medals and shown on the leaderboard.<br>\n        bots_only: Only Bots are included in ranks/prizes/medals. Non-bots are still shown.<br>\n        ",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            code=migrate,
            reverse_code=reverse_migrate,
        ),
        migrations.RemoveField(
            model_name="project",
            name="include_bots_in_leaderboard",
        ),
    ]
