# Generated by Django 5.1.8 on 2025-05-19 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_remove_project_include_bots_in_leaderboard_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="section",
        ),
    ]
