# Generated by Django 5.1.9 on 2025-06-24 20:15

from django.db import migrations, models


def migrate_leaderboard_tags(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    Project.objects.filter(type="tag", name__endswith="Leaderboard").update(
        type="leaderboard_tag"
    )
    Project.objects.filter(type="tag").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_project_forecasters_count_project_forecasts_count"),
    ]

    operations = [
        migrations.RunPython(migrate_leaderboard_tags, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("site_main", "Site Main"),
                    ("index", "Index"),
                    ("tournament", "Tournament"),
                    ("question_series", "Question Series"),
                    ("personal_project", "Personal Project"),
                    ("news_category", "News Category"),
                    ("category", "Category"),
                    ("leaderboard_tag", "Leaderboard Tag"),
                    ("topic", "Topic"),
                    ("community", "Community"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
