# Generated by Django 5.1.9 on 2025-09-01 11:28

from django.db import migrations, models


def migrate(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.exclude(meta_description=""):
        project.html_metadata_json = {"description": project.meta_description}
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_alter_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="html_metadata_json",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Custom JSON for HTML meta tags. Supported fields are: title, description",
                null=True,
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="project",
            name="meta_description",
        ),
    ]
