# Generated by Django 5.1.11 on 2025-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_anonymous_forecasting",
            field=models.BooleanField(
                default=False,
                help_text="When a logged out user comes to the tournament page while the tournament is ongoing, they will be prompted to consent to cookies, then given an anonymous account.<br>This field also permits anonymous users to forecast on questions in the tournament (whose post.default_project is this project).",
            ),
        ),
    ]
