# Generated by Django 5.1.11 on 2025-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_quick_signup",
            field=models.BooleanField(
                default=False,
                help_text="Allow sign up with minimal validation on this project page.",
            ),
        ),
    ]
