# Generated by Django 5.1.9 on 2025-08-22 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_index_data(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectIndex = apps.get_model("projects", "ProjectIndex")
    ProjectIndexPost = apps.get_model("projects", "ProjectIndexPost")

    index_projects = Project.objects.filter(type="index")

    # Create index object for each project
    for project in index_projects:
        index = ProjectIndex.objects.create()
        project.index = index
        project.save()

        for project_index in project.index_questions.all():
            ProjectIndexPost.objects.create(
                index=index,
                post=(
                    getattr(project_index.question, "post", None)
                    or getattr(project_index.question.group, "post", None)
                ),
                weight=project_index.weight,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_alter_post_hotness"),
        ("projects", "0019_alter_project_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("default", "Default"), ("multi_year", "Multi Year")],
                        default="default",
                        max_length=32,
                    ),
                ),
                (
                    "min_label",
                    models.CharField(
                        blank=True,
                        help_text="Label at the minimum end of the scale (left). Example: “Less democratic”",
                        max_length=200,
                    ),
                ),
                (
                    "max_label",
                    models.CharField(
                        blank=True,
                        help_text="Label at the maximum end of the scale (right). Example: “More democratic”",
                        max_length=200,
                    ),
                ),
                (
                    "increasing_is_good",
                    models.BooleanField(
                        default=True,
                        help_text="Color polarity: if on, higher values are good (green → right, red → left); if off, invert the colors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Index",
                "verbose_name_plural": "Indexes",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="index",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project",
                to="projects.projectindex",
            ),
        ),
        migrations.CreateModel(
            name="ProjectIndexPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                (
                    "weight",
                    models.FloatField(
                        help_text="Weight of the post within the index. If the post includes a group of questions, the same weight will be applied to all subquestions.",
                        default=1.0,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Will be displayed ordered by this field inside each section",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_weights",
                        to="projects.projectindex",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Index Post",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index", "post"),
                        name="projectindexpost_unique_project_question",
                    )
                ],
            },
        ),
        migrations.RunPython(migrate_index_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ProjectIndexQuestion",
        ),
    ]
