# Generated by Django 5.1.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_projectindex_project_index_projectindexpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsubscription",
            name="follow_questions",
            field=models.BooleanField(default=False),
        ),
    ]
