# Generated by Django 5.1.11 on 2025-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_projectindex_project_index_projectindexpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_forecast_resubmission",
            field=models.BooleanField(
                default=True,
                help_text="Turning this off prevents users from submitting multiple forecasts on any question where this is it's default_project. Forecasts submitted on those questions will always have infinite duration, ignoring auto-withdrawal.",
            ),
        ),
    ]
