# Generated by Django 5.2.11 on 2026-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_projectsubscription_follow_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="bot_leaderboard_status",
            field=models.CharField(
                choices=[
                    ("exclude_and_hide", "Exclude And Hide"),
                    ("exclude_and_show", "Exclude And Show"),
                    ("include", "Include"),
                    ("bots_only", "Bots Only"),
                ],
                db_index=True,
                default="exclude_and_show",
                help_text="Sets the status of bots in any leaderboard associated with this project.<br>\n        exclude_and_hide: Bots are excluded from ranks/prizes/medals and hidden from the leaderboard.<br>\n        exclude_and_show: Bots are excluded from ranks/prizes/medals but shown on the leaderboard.<br>\n        include: Bots are included in ranks/prizes/medals and shown on the leaderboard.<br>\n        bots_only: Only Bots are included in ranks/prizes/medals. Non-bots are still shown.<br>\n        ",
                max_length=32,
            ),
        ),
    ]
