# Generated by Django 5.0.6 on 2024-06-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="forecast",
            new_name="included_forecast",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="question",
            new_name="on_question",
        ),
    ]
