# Generated by Django 5.0.6 on 2024-07-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0004_rename_closed_at_post_actual_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
