# Generated by Django 5.0.6 on 2024-06-07 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_rename_forecast_comment_included_forecast_and_more"),
        ("projects", "0006_alter_project_section"),
        ("questions", "0006_alter_question_type_alter_vote_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="on_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="on_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.question",
            ),
        ),
    ]
