# Generated by Django 5.0.6 on 2024-07-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_on_post"),
        ("projects", "0003_project_primary_leaderboard"),
        ("questions", "0007_question_cp_reveal_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="edit_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="comment",
            name="included_forecast",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.forecast",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="on_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comments.comment",
            ),
        ),
    ]
