# Generated by Django 5.0.6 on 2024-06-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_comment_on_project_alter_comment_on_question"),
        ("posts", "__first__"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="on_question",
        ),
        migrations.AddField(
            model_name="comment",
            name="on_post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
        ),
    ]
