# Generated by Django 5.1.1 on 2024-10-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_private",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
