# Generated by Django 5.1.1 on 2024-11-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_alter_comment_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content_last_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_original_lang",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_cs",
            field=models.TextField(null=True, max_length=150000),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_en",
            field=models.TextField(null=True, max_length=150000),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_es",
            field=models.TextField(null=True, max_length=150000),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_original",
            field=models.TextField(null=True, max_length=150000),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_zh",
            field=models.TextField(null=True, max_length=150000),
        ),
    ]
