# Generated by Django 5.1.1 on 2024-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_new',
            field=models.TextField(null=True),
        ),
    ]
