# Generated by Django 5.1.1 on 2024-11-13 15:49

from django.db import migrations
from utils.translation import migration_update_default_fields


def migrate(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    migration_update_default_fields(Comment, ["text"])


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_comment_content_last_md5_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
