# Generated by Django 5.1.1 on 2024-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_populate_original_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text_pt",
            field=models.TextField(null=True, max_length=150000),
        ),
    ]
