# Generated by Django 5.1.1 on 2024-11-20 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_comment_text_pt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_last_md5",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "content_original_lang",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        editable=False, null=True
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("text_original", models.TextField(blank=True, null=True)),
                ("text_en", models.TextField(blank=True, null=True)),
                ("text_cs", models.TextField(blank=True, null=True)),
                ("text_es", models.TextField(blank=True, null=True)),
                ("text_zh", models.TextField(blank=True, null=True)),
                ("text_pt", models.TextField(blank=True, null=True)),
                (
                    "votes_score",
                    models.IntegerField(db_index=True, default=0, editable=False),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_factors",
                        to="comments.comment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeyFactorVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        editable=False, null=True
                    ),
                ),
                (
                    "score",
                    models.SmallIntegerField(
                        choices=[(1, "Up"), (-1, "Down")], db_index=True
                    ),
                ),
                (
                    "key_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="comments.keyfactor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_factor_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key_factor", "score"],
                        name="comments_ke_key_fac_5e8be8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "key_factor_id"),
                        name="votes_unique_user_key_factor",
                    )
                ],
            },
        ),
    ]
