# Generated by Django 5.0.6 on 2024-08-08 15:21

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def set_comments_root(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    Comment.objects.update(root=F("parent"))


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0007_changedmymindentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="thread_comments",
                to="comments.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_comments",
                to="comments.comment",
            ),
        ),
        migrations.RunPython(set_comments_root, reverse_code=migrations.RunPython.noop),
    ]
