# Generated by Django 5.1.1 on 2024-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0008_keyfactor_keyfactorvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_soft_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
