# Generated by Django 5.1.4 on 2025-03-03 17:57

from django.db import migrations, models
from django.db.models import F


def migrate_text_edited_at(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    Comment.objects.update(text_edited_at=F("edited_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0009_alter_comment_is_soft_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text_edited_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(migrate_text_edited_at, migrations.RunPython.noop),
    ]
