# Generated by Django 5.1.4 on 2025-03-03 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0010_comment_text_edited_at"),
        ("posts", "0013_alter_post_hotness"),
        ("projects", "0011_alter_project_type_projectindexquestion"),
        ("questions", "0015_remove_forecast_distribution_components_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_pinned", False), ("root__isnull", True), _connector="OR"
                ),
                name="comment_check_pinned_comment_is_root",
            ),
        ),
    ]
