# Generated by Django 5.1.4 on 2025-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0011_comment_is_pinned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_automatically_translated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="keyfactor",
            name="is_automatically_translated",
            field=models.BooleanField(default=True),
        ),
    ]
