# Generated by Django 5.1.7 on 2025-04-10 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0012_comment_is_automatically_translated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="keyfactorvote",
            name="votes_unique_user_key_factor",
        ),
        migrations.AddField(
            model_name="keyfactorvote",
            name="vote_type",
            field=models.CharField(
                choices=[
                    ("a_updown", "A Upvote Downvote"),
                    ("b_2step", "B Two Step Survey"),
                    ("c_likert", "C Likert Scale"),
                ],
                default="a_updown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="keyfactorvote",
            name="score",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Up"),
                    (-1, "Down"),
                    (-5, "Decrease High"),
                    (-3, "Decrease Medium"),
                    (-2, "Decrease Low"),
                    (0, "No Impact"),
                    (2, "Increase Low"),
                    (3, "Increase Medium"),
                    (5, "Increase High"),
                ],
                db_index=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="keyfactorvote",
            constraint=models.UniqueConstraint(
                fields=("user_id", "key_factor_id", "vote_type"),
                name="votes_unique_user_key_factor",
            ),
        ),
    ]
