# Generated by Django 5.1.7 on 2025-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0013_remove_keyfactorvote_votes_unique_user_key_factor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text_zh_TW",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="keyfactor",
            name="text_zh_TW",
            field=models.TextField(blank=True, null=True),
        ),
    ]
