# Generated by Django 5.1.10 on 2025-08-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0014_comment_text_zh_tw_keyfactor_text_zh_tw"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentsOfTheWeekEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("week_start_date", models.DateField()),
                ("score", models.FloatField(default=0)),
                ("excluded", models.BooleanField(default=False)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_of_the_week_entry",
                        to="comments.comment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
