# Generated by Django 5.1.10 on 2025-08-14 20:23

from django.db import migrations, models
from django.db.models import F, Func, Value


def unsubscribe_all_from_weekly_top_comments(apps, schema_editor):
    User = apps.get_model("users", "User")
    weekly_tag = "weekly_top_comments"

    # Unsubscribe all users by adding the tag to their unsubscribed_mailing_tags
    User.objects.exclude(unsubscribed_mailing_tags__contains=[weekly_tag]).update(
        unsubscribed_mailing_tags=Func(
            F("unsubscribed_mailing_tags"),
            Value(weekly_tag),
            function="array_append",
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0015_commentsoftheweekentry"),
    ]

    operations = [
        migrations.RunPython(
            unsubscribe_all_from_weekly_top_comments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="CommentsOfTheWeekNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("week_start_date", models.DateField()),
                ("email_sent", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
