# Generated by Django 5.1.10 on 2025-09-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_commentsoftheweekentry_votes_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyFactor',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='KeyFactorVote',
            new_name='DriverVote',
        ),
    ]