# Generated by Django 5.1.10 on 2025-10-01 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0018_rename_key_factors"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Driver",
            new_name="KeyFactor",
        ),
        migrations.RenameModel(
            old_name="DriverVote",
            new_name="KeyFactorVote",
        ),
        migrations.RenameIndex(
            model_name="keyfactorvote",
            new_name="comments_ke_key_fac_5e8be8_idx",
            old_name="comments_dr_key_fac_8375c5_idx",
        ),
    ]

