# Generated by Django 5.1.10 on 2025-10-02 19:31
import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def calculate_votes_strength(scores: list[int]):
    """
    Calculates overall strengths of the KeyFactor
    """

    return (sum(scores) + 2 * max(0, 3 - len(scores))) / max(3, len(scores))


def migrate_strength_vote_score(score: int):
    # Converting (-5, -3, -2, 0, 2, 3, 5) scale to (0, 1, 2, 5)
    score = abs(score)

    return {
        0: 0,  # No
        2: 1,  # Low
        3: 2,  # Medium
        5: 5,  # High
    }[score]


def votes_migration(apps, schema_editor):
    KeyFactorVote = apps.get_model("comments", "KeyFactorVote")
    KeyFactor = apps.get_model("comments", "KeyFactor")
    KeyFactorDriver = apps.get_model("comments", "KeyFactorDriver")

    # Drop unused a_updown votes
    KeyFactorVote.objects.filter(vote_type="a_updown").delete()

    # There could be cases when users might have multiple vote types against one KeyFactor
    # So deleting other duplicates
    votes_qs = KeyFactorVote.objects.order_by(
        "key_factor_id", "user_id", "-created_at"
    ).distinct("key_factor_id", "user_id")

    to_delete = KeyFactorVote.objects.exclude(pk__in=votes_qs)
    logger.info(f"Deleting {to_delete.count()} duplicated KeyFactor votes")

    to_delete.delete()

    # Migrate other votes
    key_factors = list(
        KeyFactor.objects.select_related("comment").prefetch_related("votes").all()
    )
    update_votes = []
    update_drivers = []

    for kf in key_factors:
        votes = kf.votes.all()

        if not votes:
            logger.info(f"KeyFactor {kf.id} has no votes")
            continue

        votes_sum = sum([v.score for v in votes])
        author_vote_score = next(
            (v.score for v in votes if v.user_id == kf.comment.author_id), None
        )

        # Author's vote has more weight
        direction = author_vote_score or votes_sum

        if direction == 0:
            logger.info(f"KeyFactor {kf.id} has direction = 0")
        else:
            # Update driver direction
            kf.driver.impact_direction = 1 if direction > 0 else -1
            update_drivers.append(kf.driver)

        for vote in votes:
            # Update vote type
            vote.vote_type = "strength"

            if (direction > 0 and vote.score < 0) or (direction < 0 and vote.score > 0):
                # votes that disagree with the new direction get strength 0
                vote.score = 0
            else:
                # votes that agree keep their abs strength,
                # but are converted to the (0, 1, 2, 5) scale
                vote.score = migrate_strength_vote_score(vote.score)

            update_votes.append(vote)

        # Calculate strength
        kf.votes_score = (
            calculate_votes_strength([v.score for v in votes]) if votes else 0
        )

    logger.info(f"Updating {len(update_votes)} votes")
    KeyFactorVote.objects.bulk_update(update_votes, ["score", "vote_type"])
    logger.info(f"Updating {len(update_drivers)} drivers")
    KeyFactorDriver.objects.bulk_update(update_drivers, ["impact_direction"])
    KeyFactor.objects.bulk_update(key_factors, ["votes_score"])


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0019_keyfactors_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyfactor",
            name="votes_score",
            field=models.FloatField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="keyfactordriver",
            name="impact_direction",
            field=models.SmallIntegerField(
                blank=True, choices=[(1, "Increase"), (-1, "Decrease")], null=True
            ),
        ),
        migrations.RunPython(votes_migration, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="keyfactorvote",
            name="votes_unique_user_key_factor",
        ),
        migrations.AddConstraint(
            model_name="keyfactorvote",
            constraint=models.UniqueConstraint(
                fields=("user_id", "key_factor_id"), name="votes_unique_user_key_factor"
            ),
        ),
        migrations.AlterField(
            model_name="keyfactorvote",
            name="vote_type",
            field=models.CharField(
                choices=[("strength", "Strength"), ("direction", "Direction")],
                default="direction",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="keyfactordriver",
            name="certainty",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
