# Generated by Django 5.1.13 on 2025-11-03 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0020_keyfactors_votes_migration_and_cleanup"),
        ("questions", "0030_alter_question_cp_reveal_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyFactorBaseRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_last_md5",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "content_original_lang",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("is_automatically_translated", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("reference_class", models.CharField(max_length=256)),
                (
                    "type",
                    models.CharField(
                        choices=[("frequency", "Frequency"), ("trend", "Trend")],
                        max_length=20,
                    ),
                ),
                ("rate_numerator", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rate_denominator",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("projected_value", models.FloatField(blank=True, null=True)),
                ("projected_by_year", models.IntegerField(blank=True, null=True)),
                ("unit", models.CharField(max_length=25)),
                (
                    "extrapolation",
                    models.CharField(
                        blank=True,
                        choices=[("frequency", "Frequency"), ("trend", "Trend")],
                        default="",
                        max_length=32,
                    ),
                ),
                ("based_on", models.CharField(blank=True, default="", max_length=256)),
                ("source", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="keyfactor",
            name="driver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="key_factor",
                to="comments.keyfactordriver",
            ),
        ),
        migrations.AddField(
            model_name="keyfactor",
            name="base_rate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="base_rate",
                to="comments.keyfactorbaserate",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyfactor",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    lhs=models.Func(
                        "driver",
                        "base_rate",
                        function="num_nonnulls",
                        output_field=models.IntegerField(),
                    ),
                    rhs=models.Value(1),
                ),
                name="num_nonnulls_check",
            ),
        ),
    ]
