# Generated by Django 5.1.13 on 2025-11-06 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0021_keyfactorbaserate_alter_keyfactor_driver_and_more"),
        ("misc", "0006_whitelistuser_notes_and_more"),
        ("questions", "0030_alter_question_cp_reveal_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyFactorNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("url", models.CharField(default="", max_length=2000)),
                ("title", models.CharField(default="", max_length=500)),
                ("img_url", models.CharField(blank=True, default="", max_length=2000)),
                ("source", models.CharField(default="", max_length=255)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="keyfactor",
            name="num_nonnulls_check",
        ),
        migrations.AlterField(
            model_name="keyfactor",
            name="base_rate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="key_factor",
                to="comments.keyfactorbaserate",
            ),
        ),
        migrations.AddField(
            model_name="keyfactornews",
            name="itn_news",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="key_factor_news",
                to="misc.itnarticle",
            ),
        ),
        migrations.AddField(
            model_name="keyfactor",
            name="news",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="key_factor",
                to="comments.keyfactornews",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyfactor",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    lhs=models.Func(
                        "driver",
                        "base_rate",
                        "news",
                        function="num_nonnulls",
                        output_field=models.IntegerField(),
                    ),
                    rhs=models.Value(1),
                ),
                name="num_nonnulls_check",
            ),
        ),
    ]
