# Generated by Django 5.1.15 on 2025-12-16 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0022_keyfactor_news"),
        ("posts", "0027_alter_postusersnapshot_private_note_updated_at"),
        ("projects", "0021_projectindex_project_index_projectindexpost"),
        ("questions", "0031_forecast_questions_f_author__d4ea27_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "is_private", "on_post"],
                name="comment_user_private_post_idx",
            ),
        ),
    ]
