# Generated by Django 5.2.12 on 2026-03-17 18:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


def backfill_vote_score(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE comments_comment c
            SET vote_score = COALESCE(sub.score, 0)
            FROM (SELECT comment_id, SUM(direction) AS score
                  FROM comments_commentvote
                  GROUP BY comment_id) sub
            WHERE c.id = sub.comment_id
            """
        )
        print(f"\n  vote_score: {cursor.rowcount} rows updated")


def backfill_cmm_count(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE comments_comment c
            SET cmm_count = sub.cnt
            FROM (SELECT comment_id, COUNT(*) AS cnt
                  FROM comments_changedmymindentry
                  GROUP BY comment_id) sub
            WHERE c.id = sub.comment_id
            """
        )
        print(f"\n  cmm_count: {cursor.rowcount} rows updated")


def backfill_text_original_search_vector(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE comments_comment
            SET text_original_search_vector = to_tsvector('english', COALESCE(text_original, ''))
            WHERE text_original IS NOT NULL
              AND text_original != ''
              AND is_private = false
              AND is_soft_deleted = false
            """
        )
        print(f"\n  text_original_search_vector: {cursor.rowcount} rows updated")


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0023_comment_comment_user_private_post_idx"),
        ("posts", "0029_remove_notebook_markdown_summary_and_more"),
        ("projects", "0021_projectindex_project_index_projectindexpost"),
        ("questions", "0037_question_options_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="cmm_count",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_original_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="vote_score",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["created_at"], name="comment_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("is_private", False), ("is_soft_deleted", False)),
                fields=["text_original_search_vector"],
                name="comment_text_search_vector_idx",
            ),
        ),
        migrations.RunPython(backfill_vote_score, migrations.RunPython.noop),
        migrations.RunPython(backfill_cmm_count, migrations.RunPython.noop),
        migrations.RunPython(
            backfill_text_original_search_vector, migrations.RunPython.noop
        ),
    ]
