# Generated by Django 5.2.12 on 2026-03-16 22:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models
from django.db import connection


def backfill_vote_score(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE comments_comment c
            SET vote_score = COALESCE(sub.score, 0)
            FROM (
                SELECT comment_id, SUM(direction) AS score
                FROM comments_commentvote
                GROUP BY comment_id
            ) sub
            WHERE c.id = sub.comment_id
        """)
        print(f"\n  vote_score: {cursor.rowcount} rows updated")


def backfill_cmm_count(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE comments_comment c
            SET cmm_count = sub.cnt
            FROM (
                SELECT comment_id, COUNT(*) AS cnt
                FROM comments_changedmymindentry
                GROUP BY comment_id
            ) sub
            WHERE c.id = sub.comment_id
        """)
        print(f"\n  cmm_count: {cursor.rowcount} rows updated")


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0023_comment_comment_user_private_post_idx"),
        ("posts", "0029_remove_notebook_markdown_summary_and_more"),
        ("projects", "0021_projectindex_project_index_projectindexpost"),
        ("questions", "0037_question_options_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="cmm_count",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="vote_score",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["created_at"], name="comment_created_at_idx"),
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS comment_text_search_idx
                ON comments_comment
                USING gin (to_tsvector('english', COALESCE(text_original, '')))
                WHERE is_private = FALSE AND is_soft_deleted = FALSE;
            """,
            reverse_sql="DROP INDEX IF EXISTS comment_text_search_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name="comment",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "text_original", config="english"
                        ),
                        condition=models.Q(
                            is_private=False, is_soft_deleted=False
                        ),
                        name="comment_text_search_idx",
                    ),
                ),
            ],
        ),
        migrations.RunPython(backfill_vote_score, migrations.RunPython.noop),
        migrations.RunPython(backfill_cmm_count, migrations.RunPython.noop),
    ]
