# Generated by Django 5.2.12 on 2026-03-16 22:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models
from django.db.models import Subquery, Sum, Count, OuterRef, Value
from django.db.models.functions import Coalesce

BATCH_SIZE = 10_000


def chunked_ids(queryset, chunk_size=BATCH_SIZE):
    id_list = list(queryset.values_list("id", flat=True))
    total = len(id_list)
    for i in range(0, total, chunk_size):
        yield i, total, id_list[i : i + chunk_size]


def backfill_vote_score(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    CommentVote = apps.get_model("comments", "CommentVote")

    vote_subquery = Subquery(
        CommentVote.objects.filter(comment_id=OuterRef("pk"))
        .values("comment_id")
        .annotate(score=Sum("direction"))
        .values("score")
    )

    print(f"\nBackfilling vote_score...")
    for offset, total, chunk in chunked_ids(Comment.objects.all()):
        updated = Comment.objects.filter(pk__in=chunk).update(
            vote_score=Coalesce(vote_subquery, Value(0))
        )
        print(f"  vote_score: {offset + len(chunk)}/{total} processed, {updated} updated")
    print("  vote_score: done")


def backfill_cmm_count(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    ChangedMyMindEntry = apps.get_model("comments", "ChangedMyMindEntry")

    cmm_subquery = Subquery(
        ChangedMyMindEntry.objects.filter(comment_id=OuterRef("pk"))
        .values("comment_id")
        .annotate(cnt=Count("id"))
        .values("cnt")
    )

    print(f"\nBackfilling cmm_count...")
    for offset, total, chunk in chunked_ids(Comment.objects.all()):
        updated = Comment.objects.filter(pk__in=chunk).update(
            cmm_count=Coalesce(cmm_subquery, Value(0))
        )
        print(f"  cmm_count: {offset + len(chunk)}/{total} processed, {updated} updated")
    print("  cmm_count: done")


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0023_comment_comment_user_private_post_idx"),
        ("posts", "0029_remove_notebook_markdown_summary_and_more"),
        ("projects", "0021_projectindex_project_index_projectindexpost"),
        ("questions", "0037_question_options_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="cmm_count",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="vote_score",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["created_at"], name="comment_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("text", config="english"),
                name="comment_text_search_idx",
            ),
        ),
        migrations.RunPython(backfill_vote_score, migrations.RunPython.noop),
        migrations.RunPython(backfill_cmm_count, migrations.RunPython.noop),
    ]
