# Generated by Django 5.2.11 on 2026-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0024_add_denormalized_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyfactorvote",
            name="vote_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wrong_direction", "Wrong Direction"),
                    ("no_impact", "No Impact"),
                    ("redundant", "Redundant"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
