# Generated by Django 5.2.11 on 2026-04-01 15:07
import numpy as np
from django.db import migrations, models


def backfill_key_factor_votes_score(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")

    comments = (
        Comment.objects.filter(key_factors__votes__isnull=False)
        .distinct()
        .only("key_factors__votes__score", "key_factor_votes_score")
        .prefetch_related("key_factors__votes")
    )
    to_update = []
    for comment in comments:
        score = 0.0
        for kf in comment.key_factors.all():
            votes = [abs(v.score) for v in kf.votes.all()]
            if votes:
                score += np.mean(votes)
        if score:
            comment.key_factor_votes_score = score
            to_update.append(comment)

    Comment.objects.bulk_update(to_update, ["key_factor_votes_score"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0025_keyfactorvote_vote_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="key_factor_votes_score",
            field=models.FloatField(db_index=True, default=0, editable=False),
        ),
        migrations.RunPython(
            backfill_key_factor_votes_score, migrations.RunPython.noop
        ),
    ]
