# Generated by Django 5.2.15 on 2026-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0026_comment_key_factor_votes_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_text_archived',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='True if the full text has been moved to S3 and only a truncated stub remains in the text columns. Archived comments cannot be edited; use the comment-detail endpoint to read them.'),
        ),
    ]
