# Generated by Django 4.2.11 on 2024-07-18 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Keeps track of input token used. Filled in automatically",
                    ),
                ),
                (
                    "output_tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Keeps track of output token used. Filled in automatically",
                    ),
                ),
                (
                    "total_allowed_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Used by admins to set the total number of input&output tokens the user can use.",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("OPENAI", "Openai"), ("ANTHROPIC", "Anthropic")],
                        default="OPENAI",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "platform")},
            },
        ),
    ]
