# Generated by Django 5.1.1 on 2024-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Keeps track of input token used. Filled in automatically",
                    ),
                ),
                (
                    "output_tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Keeps track of output token used. Filled in automatically",
                    ),
                ),
                (
                    "total_allowed_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Used by admins to set the total number of input&output tokens the user can use.",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("OPENAI", "Openai"), ("ANTHROPIC", "Anthropic")],
                        default="OPENAI",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("gpt-4o", "gpt-4o"),
                            ("gpt-4o-mini", "gpt-4o-mini"),
                            ("gpt-4o-2024-05-13", "gpt-4o-2024-05-13"),
                            ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                            ("gpt-3.5-turbo-instruct", "gpt-3.5-turbo-instruct"),
                            (
                                "claude-3-5-sonnet-20240620",
                                "claude-3-5-sonnet-20240620",
                            ),
                            ("claude-3-opus-20240229", "claude-3-opus-20240229"),
                            ("claude-3-sonnet-20240229", "claude-3-sonnet-20240229"),
                            ("claude-3-haiku-20240307", "claude-3-haiku-20240307"),
                        ],
                        default="gpt-4o",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
