# Generated by Django 4.2.11 on 2024-07-18 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fab_credits", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userusage",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userusage",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4o-2024-05-13", "gpt-4o-2024-05-13"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-instruct", "gpt-3.5-turbo-instruct"),
                    ("claude-3-5-sonnet-20240620", "claude-3-5-sonnet-20240620"),
                    ("claude-3-opus-20240229", "claude-3-opus-20240229"),
                    ("claude-3-sonnet-20240229", "claude-3-sonnet-20240229"),
                    ("claude-3-haiku-20240307", "claude-3-haiku-20240307"),
                ],
                default="gpt-4o",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userusage",
            unique_together={("user", "platform", "model_name")},
        ),
    ]
