# Generated by Django 5.1.1 on 2024-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fab_credits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userusage",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o-2024-05-13", "gpt-4o-2024-05-13"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-instruct", "gpt-3.5-turbo-instruct"),
                    ("claude-3-5-sonnet-20240620", "claude-3-5-sonnet-20240620"),
                    ("claude-3-opus-20240229", "claude-3-opus-20240229"),
                    ("claude-3-sonnet-20240229", "claude-3-sonnet-20240229"),
                    ("claude-3-haiku-20240307", "claude-3-haiku-20240307"),
                    ("claude-3-5-sonnet-20241022", "claude-3-5-sonnet-20241022"),
                ],
                default="gpt-4o",
                max_length=50,
            ),
        ),
    ]
