# Generated by Django 5.0.8 on 2024-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fab_credits",
            "0002_alter_userusage_unique_together_userusage_model_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userusage",
            name="model_name",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "gpt-4o"),
                    ("gpt-4o-mini", "gpt-4o-mini"),
                    ("gpt-4o-2024-05-13", "gpt-4o-2024-05-13"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-instruct", "gpt-3.5-turbo-instruct"),
                    ("claude-3-5-sonnet-20240620", "claude-3-5-sonnet-20240620"),
                    ("claude-3-opus-20240229", "claude-3-opus-20240229"),
                    ("claude-3-sonnet-20240229", "claude-3-sonnet-20240229"),
                    ("claude-3-haiku-20240307", "claude-3-haiku-20240307"),
                ],
                default="gpt-4o",
                max_length=50,
            ),
        ),
    ]
