# Generated by Django 5.1.15 on 2026-01-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_tokens_and_drop_old_table(apps, schema_editor):
    """Copy tokens from old authtoken_token table and drop it."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT table_name FROM information_schema.tables
            WHERE table_name = 'authtoken_token'
            """
        )
        if cursor.fetchone():
            cursor.execute(
                """
                INSERT INTO authentication_apikey (key, user_id, created, last_used_at)
                SELECT key, user_id, created, NULL
                FROM authtoken_token
                ON CONFLICT (key) DO NOTHING
                """
            )
            cursor.execute("DROP TABLE authtoken_token")


def restore_old_table_from_new(apps, schema_editor):
    """Recreate old authtoken_token table and copy data back for rollback."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS authtoken_token (
                key VARCHAR(40) PRIMARY KEY,
                created TIMESTAMP WITH TIME ZONE NOT NULL,
                user_id INTEGER NOT NULL UNIQUE REFERENCES users_user(id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            )
            """
        )
        cursor.execute(
            """
            INSERT INTO authtoken_token (key, user_id, created)
            SELECT key, user_id, created
            FROM authentication_apikey
            ON CONFLICT (key) DO NOTHING
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_key",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            migrate_tokens_and_drop_old_table,
            reverse_code=restore_old_table_from_new,
        ),
    ]
