# Generated by Django 5.0.8 on 2024-08-14 16:32

import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ITNArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("aid", models.BigIntegerField(unique=True)),
                ("title", models.CharField()),
                ("text", models.CharField()),
                ("url", models.CharField()),
                ("img_url", models.CharField(default="")),
                ("favicon_url", models.CharField(default="")),
                ("media_name", models.CharField(default="")),
                ("media_label", models.CharField(default="")),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        help_text="Vector embeddings of the ITN Article content",
                        null=True,
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
