# Generated by Django 5.0.8 on 2024-08-13 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0001_initial"),
        ("posts", "0021_rename_cp_threshold_postsubscription_cp_change_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostITNArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("distance", models.FloatField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.itnarticle",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.post"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="postitnarticle",
            constraint=models.UniqueConstraint(
                fields=("article_id", "post_id"),
                name="post_itn_article_unique_article_post",
            ),
        ),
    ]
