# Generated by Django 5.0.8 on 2024-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itnarticle",
            name="media_label",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itnarticle",
            name="media_name",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itnarticle",
            name="text",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
