# Generated by Django 5.0.8 on 2024-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0002_itnarticle_media_label_itnarticle_media_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itnarticle",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="itnarticle",
            name="favicon_url",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="itnarticle",
            name="img_url",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="itnarticle",
            name="media_label",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="itnarticle",
            name="media_name",
            field=models.CharField(default=""),
        ),
    ]
