# Generated by Django 5.1.8 on 2025-05-19 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0004_postarticle"),
        ("posts", "0019_post_html_metadata_json"),
        ("projects", "0016_remove_project_include_bots_in_leaderboard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SidebarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display label for the sidebar item. For URL items, this must be set. For Post or Project items, it overrides the default title if provided.",
                        max_length=200,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional emoji or icon to display alongside the item name.",
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hot_topics", "Hot Topics"),
                            ("hot_categories", "Hot Categories"),
                        ],
                        default="",
                        help_text="Assign the item to a sidebar section. If left blank, the item appears above all defined sections.",
                        max_length=32,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional full or relative URL. If set, the item links to this URL instead of a Post or Project.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Determines the display order within its section. Lower numbers appear first.",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If provided, the item links to the specified Post.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="posts.post",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If provided, the item links to the specified Project.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ("section", "order", "created_at"),
            },
        ),
    ]
