# Generated by Django 5.1.9 on 2025-06-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0005_sidebaritem"),
        ("posts", "0019_post_html_metadata_json"),
        ("projects", "0018_project_forecasters_count_project_forecasts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelistuser",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about the whitelisting, e.g., reason for access. Please note any specific conditions.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whitelistuser",
            name="view_deanonymized_data",
            field=models.BooleanField(
                default=False,
                help_text="If False, all downloaded data will be anonymized.",
            ),
        ),
        migrations.AlterField(
            model_name="whitelistuser",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. If provided, this allows the user to download user-level data for the post. If neither project nor post is set, the user is whitelisted for all data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whitelists",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="whitelistuser",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. If provided, this allows the user to download user-level data for the project. If neither project nor post is set, the user is whitelisted for all data.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whitelists",
                to="projects.project",
            ),
        ),
    ]
