# Generated by Django 5.1.13 on 2025-11-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0006_whitelistuser_notes_and_more"),
        ("posts", "0025_post_actual_resolve_time"),
        ("projects", "0021_projectindex_project_index_projectindexpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. If set, places this Bulletin only on this post's page.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. If set, places this Bulletin only on this project's page.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
