# Generated by Django 5.1.15 on 2026-03-16 15:16

from django.db import migrations, models


def set_existing_view_user_data(apps, schema_editor):
    """All pre-existing entries were created for user data access, so set view_user_data=True."""
    UserDataAccess = apps.get_model("misc", "UserDataAccess")
    UserDataAccess.objects.all().update(view_user_data=True)


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0007_bulletin_post_bulletin_project"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WhitelistUser",
            new_name="UserDataAccess",
        ),
        migrations.AddField(
            model_name="userdataaccess",
            name="api_access_tier",
            field=models.CharField(
                choices=[
                    ("restricted", "Restricted"),
                    ("benchmarking", "Benchmarking"),
                    ("unrestricted", "Unrestricted"),
                ],
                default="restricted",
                help_text="Indicates the API access tier relevant to this data access entry.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userdataaccess",
            name="view_user_data",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If True, the user can view user-level data (e.g., download datasets "
                    "with user-level information included). If False, the user can only access "
                    "aggregated data or anonymized user-level data."
                ),
            ),
        ),
        migrations.RunPython(
            set_existing_view_user_data,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="userdataaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="data_accesses",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="userdataaccess",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional. Scopes this entry to a specific project. "
                    "If neither project nor post is set while `view_user_data` is True, this entry "
                    "will apply globally with respect to viewing user data. "
                    "The API access tier will apply to this project if it exceeds the user's "
                    "base tier. If neither project nor post is set, the api_access_tier will be "
                    "taken from the User's base tier."
                ),
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="data_accesses",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="userdataaccess",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional. Scopes this entry to a specific post. "
                    "The API access tier will apply to this post if it exceeds the user's "
                    "base tier. If neither project nor post is set, the entry applies globally."
                ),
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="data_accesses",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="userdataaccess",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about the data access grant, e.g., reason for access. Please note any specific conditions.",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdataaccess",
            unique_together={("user", "project", "post")},
        ),
        migrations.AddConstraint(
            model_name="userdataaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(project__isnull=True)
                | models.Q(post__isnull=True), 
                name="userdataaccess_project_or_post_not_both",
            ),
        ),
    ]
