# Generated by Django 5.1.15 on 2026-03-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0007_bulletin_post_bulletin_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelistuser",
            name="view_forecaster_data",
            field=models.BooleanField(
                default=True,
                help_text="If True, allows the user to view forecaster-level data (e.g, individual user predictions). If False, this Whitelist is just an api-restriction reduction for the relevant projects",
            ),
        ),
    ]
