# Generated by Django 5.1.15 on 2026-03-16 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_whitelistuser_to_userdataaccess(apps, schema_editor):
    WhitelistUser = apps.get_model("misc", "WhitelistUser")
    UserDataAccess = apps.get_model("misc", "UserDataAccess")
    for entry in WhitelistUser.objects.all():
        UserDataAccess.objects.create(
            id=entry.id,
            created_at=entry.created_at,
            edited_at=entry.edited_at,
            user=entry.user,
            project=entry.project,
            post=entry.post,
            notes=entry.notes,
            view_deanonymized_data=entry.view_deanonymized_data,
            api_access_tier="restricted",
            view_user_data=True,
        )


def copy_userdataaccess_to_whitelistuser(apps, schema_editor):
    UserDataAccess = apps.get_model("misc", "UserDataAccess")
    WhitelistUser = apps.get_model("misc", "WhitelistUser")
    for entry in UserDataAccess.objects.all():
        WhitelistUser.objects.create(
            id=entry.id,
            created_at=entry.created_at,
            edited_at=entry.edited_at,
            user=entry.user,
            project=entry.project,
            post=entry.post,
            notes=entry.notes,
            view_deanonymized_data=entry.view_deanonymized_data,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0007_bulletin_post_bulletin_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                (
                    "api_access_tier",
                    models.CharField(
                        choices=[
                            ("restricted", "Restricted"),
                            ("benchmarking", "Benchmarking"),
                            ("unrestricted", "Unrestricted"),
                        ],
                        default="restricted",
                        help_text="Indicates the API access tier relevant to this data access entry.",
                        max_length=32,
                    ),
                ),
                (
                    "view_user_data",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "If True, the user can view user-level data (e.g., download datasets "
                            "with user-level information included). If False, the user can only access "
                            "aggregated data or anonymized user-level data."
                        ),
                    ),
                ),
                (
                    "view_deanonymized_data",
                    models.BooleanField(
                        default=False,
                        help_text="If False, all downloaded data will be anonymized.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the data access grant, e.g., reason for access. Please note any specific conditions.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Optional. Scopes this entry to a specific project. "
                            "If neither project nor post is set while `view_user_data` is True, this entry "
                            "will apply globally with respect to viewing user data. "
                            "The API access tier will apply to this project if it exceeds the user's "
                            "base tier. If neither project nor post is set, the api_access_tier will be "
                            "taken from the User's base tier."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_accesses",
                        to="projects.project",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Optional. Scopes this entry to a specific post. "
                            "The API access tier will apply to this post if it exceeds the user's "
                            "base tier. If neither project nor post is set, the entry applies globally."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_accesses",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="userdataaccess",
            unique_together={("user", "project", "post")},
        ),
        migrations.AddConstraint(
            model_name="userdataaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(project__isnull=True) | models.Q(post__isnull=True),
                name="userdataaccess_project_or_post_not_both",
            ),
        ),
        migrations.RunPython(
            copy_whitelistuser_to_userdataaccess,
            reverse_code=copy_userdataaccess_to_whitelistuser,
        ),
        migrations.DeleteModel(
            name="WhitelistUser",
        ),
    ]
