# Generated by Django 5.2 on 2026-05-09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0008_replace_whitelistuser_with_userdataaccess"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulletin",
            name="post",
        ),
        migrations.RemoveField(
            model_name="bulletin",
            name="project",
        ),
    ]
