# Generated by Django 5.2.14 on 2026-06-08 16:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0009_remove_bulletin_post_project"),
        ("projects", "0023_alter_project_bot_leaderboard_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required unless a Project is selected (its name is used instead).",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Call-to-action button label. If blank, no CTA button is rendered.",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Destination URL. Required unless a Project is selected (its link is used).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Master on/off switch, independent of the schedule.",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional scheduled start. Blank = immediately.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional auto-hide time. Blank = never.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers are served first."
                    ),
                ),
                (
                    "exposure_rate",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="1-100. Percentage chance of being shown (rolled on the frontend).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. Provides default title/image and de-duplicates against the auto-generated feed tile for the same project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_tiles",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-created_at"),
            },
        ),
    ]
