# Generated by Django 5.2.14 on 2026-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0010_adtile'),
    ]

    operations = [
        migrations.AddField(
            model_name='itnarticle',
            name='cluster_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='itnarticle',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
