# Generated by Django 5.2.16 on 2026-09-03 11:29

import django.contrib.postgres.fields
import misc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0011_itnarticle_cluster_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="adtile",
            name="placements",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("questions_feed", "Questions Feed"),
                        ("question_sidebar", "Question Sidebar"),
                        ("news_feed", "News Feed"),
                    ],
                    max_length=32,
                ),
                default=misc.models.default_ad_tile_placements,
                help_text="Surfaces this tile may appear on. At least one is required.",
                size=None,
            ),
        ),
    ]
