# Generated by Django 5.2.16 on 2026-09-21 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Question series "Bot benchmarking question list". Inlined rather than imported so that
# renaming or moving the constant later cannot change what this migration did. The API
# gateway hardcodes the same id to decide which questions the benchmarking level may
# read, so a global benchmarking tier only ever unlocked this one project.
BENCHMARKING_PROJECT_ID = 32979

ACCESS_LEVEL_RANK = {"restricted": 0, "benchmarking": 1, "unrestricted": 2}

MIGRATION_NOTE = (
    "Migrated automatically from the previous User.api_access_tier / "
    "UserDataAccess.api_access_tier fields."
)


def migrate_access_tiers_to_user_api_access(apps, schema_editor):
    """Fold the two old api_access_tier fields into UserApiAccess grants.

    Two deliberate asymmetries:

    - A global `benchmarking` tier becomes a grant scoped to the benchmarking project,
      not a global grant. That tier only ever unlocked that one project's questions, so
      a global grant would overstate what the user held.
    - A global `unrestricted` tier stays global, because it genuinely applied
      everywhere.

    Only project-scoped UserDataAccess tiers carry over. A tier on a row scoped to a
    post, or to nothing at all, was inert: the serializer fed the gateway only
    project-scoped entries, and the gateway took the user's base tier for everything
    else. Carrying those over would grant access nobody has today.
    """

    User = apps.get_model("users", "User")
    Project = apps.get_model("projects", "Project")
    UserDataAccess = apps.get_model("misc", "UserDataAccess")
    UserApiAccess = apps.get_model("misc", "UserApiAccess")

    grants: dict[tuple[int, int | None], str] = {}

    def record(user_id, project_id, level):
        key = (user_id, project_id)
        if ACCESS_LEVEL_RANK[level] > ACCESS_LEVEL_RANK[grants.get(key, "restricted")]:
            grants[key] = level

    # Deployments that are not metaculus.com (local, CI, forks) have no project 32979.
    # Skip the benchmarking users there rather than substituting a global grant, which
    # would hand them more than they had.
    has_benchmarking_project = Project.objects.filter(
        pk=BENCHMARKING_PROJECT_ID
    ).exists()

    for user_id, tier in User.objects.exclude(api_access_tier="restricted").values_list(
        "id", "api_access_tier"
    ):
        if tier == "unrestricted":
            record(user_id, None, tier)
        elif tier == "benchmarking" and has_benchmarking_project:
            record(user_id, BENCHMARKING_PROJECT_ID, tier)

    for user_id, project_id, tier in (
        UserDataAccess.objects.filter(project_id__isnull=False)
        .exclude(api_access_tier="restricted")
        .values_list("user_id", "project_id", "api_access_tier")
    ):
        record(user_id, project_id, tier)

    UserApiAccess.objects.bulk_create(
        [
            UserApiAccess(
                user_id=user_id,
                project_id=project_id,
                access_level=level,
                notes=MIGRATION_NOTE,
            )
            for (user_id, project_id), level in grants.items()
        ]
    )


def migrate_user_api_access_to_access_tiers(apps, schema_editor):
    """Best-effort inverse, mirroring the mapping above.

    A project-scoped grant with no matching UserDataAccess row has nowhere to go in the
    old schema and is dropped: the old fields could not express it.
    """

    User = apps.get_model("users", "User")
    UserDataAccess = apps.get_model("misc", "UserDataAccess")
    UserApiAccess = apps.get_model("misc", "UserApiAccess")

    for grant in UserApiAccess.objects.all():
        is_global_benchmarking = (
            grant.project_id == BENCHMARKING_PROJECT_ID
            and grant.access_level == "benchmarking"
        )
        if grant.project_id is None or is_global_benchmarking:
            User.objects.filter(pk=grant.user_id).update(
                api_access_tier=grant.access_level
            )
        else:
            UserDataAccess.objects.filter(
                user_id=grant.user_id, project_id=grant.project_id
            ).update(api_access_tier=grant.access_level)

    UserApiAccess.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0012_adtile_placements"),
        ("posts", "0033_postusersnapshot_posts_postuser_forecasted_idx"),
        ("projects", "0023_alter_project_bot_leaderboard_status"),
        # The data migration reads User.api_access_tier, so the migration that adds it
        # has to be in the historical state, not merely somewhere earlier in the plan.
        ("users", "0016_user_api_access_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserApiAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("benchmarking", "Benchmarking"),
                            ("unrestricted", "Unrestricted"),
                        ],
                        help_text=(
                            "The level granted at this scope. Omit the entry entirely "
                            "to leave the user restricted; the most permissive "
                            "applicable grant always wins."
                        ),
                        max_length=32,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Optional notes about the grant, e.g. who asked for it and "
                            "why. Please note any specific conditions."
                        ),
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Optional. Scopes this grant to data belonging to one "
                            "project. Leave blank to grant the level globally, on every "
                            "request the user makes."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_accesses",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user api accesses",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "project"),
                        name="userapiaccess_unique_user_project",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.RunPython(
            migrate_access_tiers_to_user_api_access,
            reverse_code=migrate_user_api_access_to_access_tiers,
        ),
    ]
