# Generated by Django 5.0.6 on 2024-07-01 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("relative_legacy", "Relative Legacy"),
                            ("peer", "Peer"),
                            ("baseline", "Baseline"),
                            ("spot_peer", "Spot Peer"),
                            ("spot_baseline", "Spot Baseline"),
                            ("comment_insight", "Comment Insight"),
                            ("question_writing", "Question Writing"),
                        ],
                        max_length=200,
                    ),
                ),
                ("score", models.FloatField()),
                ("coverage", models.FloatField(null=True)),
                ("contribution_count", models.IntegerField(default=0)),
                ("medal", models.CharField(max_length=200, null=True)),
                ("calculated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField()),
                ("coverage", models.FloatField(default=0)),
                (
                    "score_type",
                    models.CharField(
                        choices=[
                            ("relative_legacy", "Relative Legacy"),
                            ("peer", "Peer"),
                            ("baseline", "Baseline"),
                            ("spot_peer", "Spot Peer"),
                            ("spot_baseline", "Spot Baseline"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("calculated_on", models.DateTimeField(auto_now_add=True)),
                ("weight", models.FloatField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
