# Generated by Django 5.0.6 on 2024-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0002_remove_userweights_user_leaderboardentry_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="leaderboard_type",
            field=models.CharField(
                choices=[
                    ("metaculus_points", "Metaculus Points"),
                    ("peer_accuracy", "Peer Accuracy"),
                    ("baseline_accuracy", "Baseline Accuracy"),
                    ("peer_spot_forecast", "Peer Spot Forecast"),
                    ("baseline_spot_forecast", "Baseline Spot Forecast"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="score_type",
            field=models.CharField(
                choices=[
                    ("metaculus_points", "Metaculus Points"),
                    ("peer_accuracy", "Peer Accuracy"),
                    ("baseline_accuracy", "Baseline Accuracy"),
                    ("peer_spot_forecast", "Peer Spot Forecast"),
                    ("baseline_spot_forecast", "Baseline Spot Forecast"),
                ],
                max_length=200,
            ),
        ),
    ]
