# Generated by Django 5.0.6 on 2024-06-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_leaderboard_type_alter_project_type'),
        ('scoring', '0004_alter_leaderboardentry_leaderboard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='contribution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='coverage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='for_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leaderboard_type',
            field=models.CharField(choices=[('relative_legacy', 'Relative Legacy'), ('peer', 'Peer'), ('baseline', 'Baseline'), ('spot_peer', 'Spot Peer'), ('spot_baseline', 'Spot Baseline'), ('comment_insight', 'Comment Insight'), ('question_writing', 'Question Writing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('relative_legacy', 'Relative Legacy'), ('peer', 'Peer'), ('baseline', 'Baseline'), ('spot_peer', 'Spot Peer'), ('spot_baseline', 'Spot Baseline')], max_length=200),
        ),
    ]
