# Generated by Django 5.0.6 on 2024-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_leaderboardentry_leaderboard_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardentry',
            old_name='for_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='for_question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='contribution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='coverage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leaderboard_type',
            field=models.CharField(choices=[('relative_legacy', 'Relative Legacy'), ('peer', 'Peer'), ('baseline', 'Baseline'), ('spot_peer', 'Spot Peer'), ('spot_baseline', 'Spot Baseline'), ('comment_insight', 'Comment Insight'), ('question_writing', 'Question Writing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('relative_legacy', 'Relative Legacy'), ('peer', 'Peer'), ('baseline', 'Baseline'), ('spot_peer', 'Spot Peer'), ('spot_baseline', 'Spot Baseline')], max_length=200),
        ),
    ]
