# Generated by Django 5.1.1 on 2024-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0004_alter_leaderboard_score_type_alter_score_score_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="finalize_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
