# Generated by Django 5.1.4 on 2025-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0005_alter_score_aggregation_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="finalized",
            field=models.BooleanField(
                default=False,
                help_text="If true, this Leaderboard's entries cannot be updated except by a manual action in the admin panel. Automatically set to true the first time this leaderboard is updated after the finalize_time.",
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="This field is optional. It is used for:\n        <br></br>- Filtering MedalExclusionRecords: If set, MedalExclusionRecords that have a start_time less than this (and no end_time or an end_time later that this Leaderboard's start_time) will be triggered. If not set, this Leaderboard's finalize_time will be used instead.\n        <br></br>- Global Leaderboards: Required for global leaderboards, filters for questions that have a scheduled_close_time before this (plus a grace period). Automatically set, do not change.\n        <br></br>- Non-Global Leaderboards: has no effect on question filtering. Only used in filtering MedalExclusionRecords. Since finalize_time does the same thing in this case, it is recommended not to use this field.\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="finalize_time",
            field=models.DateTimeField(
                blank=True,
                help_text="This field is optional, though should generally be set (exception could include a non-concluding Leaderboard like for a Tag or Topic Leaderboard). It is used for:\n        <br></br>- Filtering MedalExclusionRecords: If set and end_time is not set, MedalExclusionRecords that have a start_time less than this (and no end_time or an end_time later that this Leaderboard's start_time) will be triggered.\n        <br></br>- For all Leaderboards: If set, used to filter out questions that have a resolution_set_time after this (as they were resolved after this Leaderboard was finalized).\n        <br></br>- Non-Global Leaderboards: This field is automatically set to the Project's close_date. If the Project's close_date is updated, this field will be updated as well. If you want this leaderboard to have a manually set finalize_time, updating this field manually will be required after each update to the Project's close_date.\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="This field is optional. It is used for:\n        <br></br>- Filtering MedalExclusionRecords: If set, MedalExclusionRecords that have no end_time or an end_time greater than this (and a start_time before this Leaderboard's end_time or finalize_time) will be triggered.\n        <br></br>- Global Leaderboards: Required for global leaderboards, filters for questions that have an open time after this. Automatically set, do not change.\n        <br></br>- Non-Global Leaderboards: has no effect on question filtering. Only used in filtering MedalExclusionRecords.\n        ",
                null=True,
            ),
        ),
    ]
