# Generated by Django 5.1.4 on 2025-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0005_alter_score_aggregation_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="excluded",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="score",
            name="score_type",
            field=models.CharField(
                choices=[
                    ("relative_legacy", "Relative Legacy"),
                    ("peer", "Peer"),
                    ("baseline", "Baseline"),
                    ("spot_peer", "Spot Peer"),
                    ("spot_baseline", "Spot Baseline"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                max_length=200,
            ),
        ),
    ]
