# Generated by Django 5.1.1 on 2025-01-14 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0006_alter_leaderboardentry_excluded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardsRanksEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("points", models.FloatField()),
                (
                    "rank_type",
                    models.CharField(
                        choices=[
                            ("tournaments", "Tournaments"),
                            ("peer_accuracy", "Peer Accuracy"),
                            ("baseline_accuracy", "Baseline Accuracy"),
                            ("comment_insight", "Comment Insight"),
                            ("question_writing", "Question Writing"),
                        ],
                        max_length=200,
                    ),
                ),
                ("rank", models.IntegerField()),
                ("rank_total", models.IntegerField()),
                ("rank_timestamp", models.DateTimeField()),
                ("best_rank", models.IntegerField(null=True)),
                ("best_rank_total", models.IntegerField(null=True)),
                ("best_rank_timestamp", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "rank_type")},
            },
        ),
    ]
