# Generated by Django 5.1.5 on 2025-03-14 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_project_add_posts_to_main_feed_and_more"),
        ("scoring", "0009_leaderboard_user_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="medalexclusionrecord",
            name="leaderboard",
            field=models.ForeignKey(
                blank=True,
                help_text="Sets the scope of this exclusion to a specific leaderboard.\n        </br>If this and project are not set, the exclusion will be universal\n        </br>Only set this or project, though not strictly enforced.\n        ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scoring.leaderboard",
            ),
        ),
        migrations.AddField(
            model_name="medalexclusionrecord",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about this exclusion.\n        Use this field for disqualified and custom exclusions.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medalexclusionrecord",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional.\n        If not set, this exclusion will extend indefinitely forwards in time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medalexclusionrecord",
            name="exclusion_type",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("project_owner", "Project Owner"),
                    ("disqualified", "Disqualified"),
                    ("other", "Other"),
                ],
                help_text="Records the type of exclusion. Use Other for custom exclusions.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="medalexclusionrecord",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Sets the scope of this exclusion to a specific project.\n        </br>If this and leaderboard are not set, the exclusion will be universal\n        </br>Only set this or leaderboard, though not strictly enforced.\n        ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="medalexclusionrecord",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Optional.\n        If not set, this exclusion will extend indefinitely backwards in time.",
                null=True,
            ),
        ),
    ]
