# Generated by Django 5.1.5 on 2025-02-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0009_leaderboard_user_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="simplified_view",
            field=models.BooleanField(default=False),
        ),
    ]
