# Generated by Django 5.1.5 on 2025-03-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0010_leaderboard_simplified_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaderboard",
            name="simplified_view",
        ),
    ]
