# Generated by Django 5.1.7 on 2025-03-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0011_medalexclusionrecord_leaderboard_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaderboard",
            name="simplified_view",
        ),
    ]
