# Generated by Django 5.1.7 on 2025-05-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0012_remove_leaderboard_simplified_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="bot_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exclude_and_hide", "Exclude And Hide"),
                    ("exclude_and_show", "Exclude And Show"),
                    ("include", "Include"),
                    ("bots_only", "Bots Only"),
                ],
                help_text="Optional. If not set, the Project's bot_leaderboard_status will be\n        used instead. See Project for more details.",
                max_length=32,
                null=True,
            ),
        ),
    ]
