# Generated by Django 5.0.8 on 2024-08-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_alter_archivedscore_aggregation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='percent_prize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='take',
            field=models.FloatField(null=True),
        ),
    ]
