# Generated by Django 5.1.8 on 2025-05-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0013_leaderboard_bot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="score_type",
            field=models.CharField(
                choices=[
                    ("peer_tournament", "Peer Tournament"),
                    ("spot_peer_tournament", "Spot Peer Tournament"),
                    ("spot_baseline_tournament", "Spot Baseline Tournament"),
                    ("relative_legacy_tournament", "Relative Legacy Tournament"),
                    ("baseline_global", "Baseline Global"),
                    ("peer_global", "Peer Global"),
                    ("peer_global_legacy", "Peer Global Legacy"),
                    ("comment_insight", "Comment Insight"),
                    ("question_writing", "Question Writing"),
                    ("manual", "Manual"),
                ],
                help_text="\n    <table>\n        <tr><td>peer_tournament</td><td> Sum of peer scores. Most likely what you want.</td></tr>\n        <tr><td>spot_peer_tournament</td><td> Sum of spot peer scores.</td></tr>\n        <tr><td>spot_baseline_tournament</td><td> Sum of spot baseline scores.</td></tr>\n        <tr><td>relative_legacy</td><td> Old site scoring.</td></tr>\n        <tr><td>baseline_global</td><td> Sum of baseline scores.</td></tr>\n        <tr><td>peer_global</td><td> Coverage-weighted average of peer scores.</td></tr>\n        <tr><td>peer_global_legacy</td><td> Average of peer scores.</td></tr>\n        <tr><td>comment_insight</td><td> H-index of upvotes for comments on questions.</td></tr>\n        <tr><td>question_writing</td><td> H-index of number of forecasters / 10 on questions.</td></tr>\n        <tr><td>manual</td><td> Does not automatically update. Manually set all entries.</td></tr>\n    </table>\n    ",
                max_length=200,
            ),
        ),
    ]
