# Generated by Django 5.1.9 on 2025-06-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0013_leaderboard_bot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="minimum_prize_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="The minimum amount a user can win in this leaderboard.\n        Any remaining money is redistributed. Tournaments that close before June 2025 will have a value of 0.00.\n        ",
                max_digits=15,
            ),
        ),
    ]
