# Generated by Django 5.1.9 on 2025-06-06 21:35

from django.db import migrations, models
from django.db.models import Q
from datetime import datetime, timezone as dt_timezone


def migrate(apps, schema_editor):
    Leaderboard = apps.get_model("scoring", "Leaderboard")
    # Set the minimum prize amount to 0.00 for all leaderboards finalized before
    # June 1, 2025
    Leaderboard.objects.filter(
        Q(finalize_time__lte=datetime(2025, 6, 1, tzinfo=dt_timezone.utc))
        | Q(
            finalize_time__isnull=True,
            project__close_date__lte=datetime(2025, 6, 1, tzinfo=dt_timezone.utc),
        )
    ).update(minimum_prize_amount=0.00)


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0013_leaderboard_bot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="minimum_prize_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="The minimum amount a user can win in this leaderboard.\n        Any remaining money is redistributed. Tournaments that close before June 2025 will have a value of 0.00.\n        ",
                max_digits=15,
            ),
        ),
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
