# Generated by Django 5.1.10 on 2025-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0015_delete_userweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="medal",
            field=models.CharField(
                blank=True,
                choices=[("gold", "Gold"), ("silver", "Silver"), ("bronze", "Bronze")],
                db_index=True,
                max_length=200,
                null=True,
            ),
        ),
    ]
