# Generated by Django 5.1.11 on 2025-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0016_alter_leaderboardentry_medal"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="show_when_excluded",
            field=models.BooleanField(
                default=False,
                help_text="If true, this entry will still be shown in the leaderboard even if\n        excluded.",
            ),
        ),
        migrations.AddField(
            model_name="medalexclusionrecord",
            name="show_anyway",
            field=models.BooleanField(
                default=False,
                help_text="If true, users excluded by this record will still appear in leaderboards.\n        <br>They will still be excluded from taking ranks and prizes.",
            ),
        ),
    ]
