# Generated by Django 5.1.13 on 2025-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0017_leaderboardentry_show_when_excluded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="ci_lower",
            field=models.FloatField(
                blank=True, help_text="Confidence Interval lower bound", null=True
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="ci_upper",
            field=models.FloatField(
                blank=True, help_text="Confidence Interval lower bound", null=True
            ),
        ),
    ]
