# Generated by Django 5.1.11 on 2025-08-15 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_project_type"),
        ("scoring", "0017_leaderboardentry_show_when_excluded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="score_type",
            field=models.CharField(
                choices=[
                    ("peer_tournament", "Peer Tournament"),
                    ("default", "Default"),
                    ("spot_peer_tournament", "Spot Peer Tournament"),
                    ("spot_baseline_tournament", "Spot Baseline Tournament"),
                    ("relative_legacy_tournament", "Relative Legacy Tournament"),
                    ("baseline_global", "Baseline Global"),
                    ("peer_global", "Peer Global"),
                    ("peer_global_legacy", "Peer Global Legacy"),
                    ("comment_insight", "Comment Insight"),
                    ("question_writing", "Question Writing"),
                    ("manual", "Manual"),
                ],
                help_text="\n    <table>\n        <tr><td>peer_tournament</td><td> Sum of peer scores. Most likely what you want.</td></tr>\n        <tr><td>default</td><td> Sum of 'Default' scores as determined by each Question's 'default_score_type'</td></tr>\n        <tr><td>spot_peer_tournament</td><td> Sum of spot peer scores.</td></tr>\n        <tr><td>spot_baseline_tournament</td><td> Sum of spot baseline scores.</td></tr>\n        <tr><td>relative_legacy</td><td> Old site scoring.</td></tr>\n        <tr><td>baseline_global</td><td> Sum of baseline scores. \n            <br> Normally only used for global leaderboards, but does work in tournaments.</td></tr>\n        <tr><td>peer_global</td><td> Coverage-weighted average of peer scores. \n            <br> Normally only used for global leaderboards. Doesn't work well in tournaments unless there are well over 50 questions.</td></tr>\n        <tr><td>peer_global_legacy</td><td> Average of peer scores. \n            <br> Only used for global leaderboards before 2024. This is not what you're looking for.</td></tr>\n        <tr><td>comment_insight</td><td> H-index of upvotes for comments on questions. \n            <br> Nromally used for global leaderboards, but can be used in tournaments.</td></tr>\n        <tr><td>question_writing</td><td> H-index of number of forecasters / 10 on questions. \n            <br> Normally used for global leaderboards, but can be used in tournaments.</td></tr>\n        <tr><td>manual</td><td> Does not automatically update. Manually set all entries.</td></tr>\n    </table>\n    ",
                max_length=200,
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("end_time__isnull", False),
                        ("project__type", "site_main"),
                        ("start_time__isnull", False),
                    ),
                    models.Q(("project__type", "site_main"), _negated=True),
                    ("project__isnull", True),
                    _connector="OR",
                ),
                name="leaderboard_project_site_main_requires_start_and_end_time",
            ),
        ),
    ]
