# Generated by Django 5.1.11 on 2025-08-15 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_project_type"),
        ("scoring", "0017_leaderboardentry_show_when_excluded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("end_time__isnull", False),
                        ("project__type", "site_main"),
                        ("start_time__isnull", False),
                    ),
                    models.Q(("project__type", "site_main"), _negated=True),
                    ("project__isnull", True),
                    _connector="OR",
                ),
                name="leaderboard_project_site_main_requires_start_and_end_time",
            ),
        ),
    ]
