# Generated by Django 5.1.13 on 2025-10-17 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0030_alter_question_cp_reveal_time"),
        ("scoring", "0018_leaderboardentry_ci_lower_leaderboardentry_ci_upper"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="score",
            index=models.Index(fields=["edited_at"], name="score_edited_at_idx"),
        ),
    ]
