# Generated by Django 5.1.15 on 2026-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0019_score_score_edited_at_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="display_config",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "Optional JSON configuration for displaying this leaderboard."
                    "<br>If not set, default display settings will be used."
                    "<br>Example display_config:"
                    "<pre>{\n"
                    '    "display_name": "My Custom Leaderboard",\n'
                    '    "column_renames": {\n'
                    '        "Questions": "Question Links"\n'
                    "    },\n"
                    '    "display_order": 1,\n'
                    '    "display_on_project": true\n'
                    "}</pre>"
                ),
                null=True,
            ),
        ),
    ]
