# Generated by Django 5.1.15 on 2026-01-31 15:26

from django.db import migrations, models
from django.db.models import BooleanField, Case, IntegerField, Value, When


def migrate(apps, schema_editor):
    LeaderboardEntry = apps.get_model("scoring", "LeaderboardEntry")
    LeaderboardEntry.objects.update(
        exclusion_status=Case(
            When(excluded=False, then=Value(0)),  # "Include"
            When(show_when_excluded=True, then=Value(2)),  # "Exclude and Show"
            default=Value(4),  # "Exclude"
            output_field=IntegerField(),
        )
    )
    MedalExclusionRecord = apps.get_model("scoring", "MedalExclusionRecord")
    MedalExclusionRecord.objects.update(
        exclusion_status=Case(
            When(show_anyway=True, then=Value(2)),  # "Exclude and Show"
            default=Value(4),  # "Exclude"
            output_field=IntegerField(),
        )
    )


def reverse_migrate(apps, schema_editor):
    LeaderboardEntry = apps.get_model("scoring", "LeaderboardEntry")
    # All values between include and exclude map to:
    #     excluded = True
    #     show_when_excluded = True
    LeaderboardEntry.objects.update(
        excluded=Case(
            When(exclusion_status=0, then=Value(False)),  # "Include"
            default=Value(True),
            output_field=BooleanField(),
        ),
        show_when_excluded=Case(
            When(exclusion_status=4, then=Value(False)),  # "Exclude"
            default=Value(True),
            output_field=BooleanField(),
        ),
    )
    MedalExclusionRecord = apps.get_model("scoring", "MedalExclusionRecord")
    MedalExclusionRecord.objects.update(
        show_anyway=Case(
            When(exclusion_status=4, then=Value(False)),  # "Exclude"
            default=Value(True),
            output_field=BooleanField(),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0020_leaderboard_display_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="exclusion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Include"),
                    (1, "Exclude Prize And Show"),
                    (2, "Exclude And Show"),
                    (3, "Exclude And Show In Advanced"),
                    (4, "Exclude"),
                ],
                default=0,
                help_text="""This sets the exclusion status of this entry.
        </br>- (0) Include: shows entry & takes rank and prize.
        </br>- (1) Exclude Prize and Show: shows entry, takes rank, but excludes from prizes
        </br>- (2) Exclude and Show: shows entry, but excludes from rank and prizes
        </br>- (3) Exclude and Show in Advanced: only shows entry in advanced views, excludes from rank and prizes
        </br>- (4) Exclude: excludes entry from showing, rank, and prizes""",
            ),
        ),
        migrations.AddField(
            model_name="medalexclusionrecord",
            name="exclusion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Include"),
                    (1, "Exclude Prize And Show"),
                    (2, "Exclude And Show"),
                    (3, "Exclude And Show In Advanced"),
                    (4, "Exclude"),
                ],
                default=4,
                help_text="""This sets the exclusion status of this entry.
        </br>- (0) Include: shows entry & takes rank and prize.
        </br>- (1) Exclude Prize and Show: shows entry, takes rank, but excludes from prizes
        </br>- (2) Exclude and Show: shows entry, but excludes from rank and prizes
        </br>- (3) Exclude and Show in Advanced: only shows entry in advanced views, excludes from rank and prizes
        </br>- (4) Exclude: excludes entry from showing, rank, and prizes""",
            ),
        ),
        migrations.RunPython(migrate, reverse_code=reverse_migrate),
    ]
