# Generated by Django 5.1.15 on 2026-02-21 19:08

from django.db import migrations, models
from django.db.models import When, Case, Value, Q


class BotLeaderboardStatus(models.TextChoices):
    EXCLUDE_AND_HIDE = "exclude_and_hide"
    EXCLUDE_AND_SHOW = "exclude_and_show"
    INCLUDE = "include"
    BOTS_ONLY = "bots_only"


def migrate(apps, schema_editor):
    Leaderboard = apps.get_model("scoring", "Leaderboard")
    Leaderboard.objects.all().update(
        bot_exclusion_status=Case(
            When(bot_status=BotLeaderboardStatus.EXCLUDE_AND_HIDE, then=Value(4)),
            When(bot_status=BotLeaderboardStatus.EXCLUDE_AND_SHOW, then=Value(2)),
            When(bot_status=BotLeaderboardStatus.INCLUDE, then=Value(0)),
            When(bot_status=BotLeaderboardStatus.BOTS_ONLY, then=Value(0)),
            default=Value(2),
        ),
        human_exclusion_status=Case(
            When(bot_status=BotLeaderboardStatus.BOTS_ONLY, then=Value(4)),
            default=Value(0),
        ),
    )

    LeaderboardEntry = apps.get_model("scoring", "LeaderboardEntry")
    LeaderboardEntry.objects.all().update(
        exclusion_status=Case(
            When(Q(excluded=True) & Q(show_when_excluded=True), then=Value(2)),
            When(Q(excluded=True) & Q(show_when_excluded=False), then=Value(4)),
            default=Value(0),
        )
    )


def reverse_migrate(apps, schema_editor):
    LeaderboardEntry = apps.get_model("scoring", "LeaderboardEntry")
    LeaderboardEntry.objects.all().update(
        excluded=Case(
            When(exclusion_status__gte=Value(2), then=Value(True)),
            default=Value(False),
        ),
        show_when_excluded=Case(
            When(exclusion_status=Value(2), then=Value(True)),
            When(exclusion_status__gte=Value(3), then=Value(False)),
            default=Value(False),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0020_leaderboard_display_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="bot_exclusion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Include"),
                    (1, "Exclude Prize Only"),
                    (2, "Exclude And Show"),
                    (3, "Exclude And Show In Advanced"),
                    (4, "Exclude"),
                ],
                default=2,
                help_text="This sets the default exclusion status for bots on this leaderboard.",
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="human_exclusion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Include"),
                    (1, "Exclude Prize Only"),
                    (2, "Exclude And Show"),
                    (3, "Exclude And Show In Advanced"),
                    (4, "Exclude"),
                ],
                default=0,
                help_text="This sets the default exclusion status for humans on this leaderboard.",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="exclusion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Include"),
                    (1, "Exclude Prize Only"),
                    (2, "Exclude And Show"),
                    (3, "Exclude And Show In Advanced"),
                    (4, "Exclude"),
                ],
                default=0,
                help_text="This sets the minimum exclusion status for this user.\n        </br>- (0) Include: shows entry & takes rank and prize.\n        </br>- (1) Exclude Prize and Show: shows entry, takes rank, but excludes from prizes\n        </br>- (2) Exclude and Show: shows entry, but excludes from rank and prizes\n        </br>- (3) Exclude and Show in Advanced: only shows entry in advanced views, excludes from rank and prizes\n        </br>- (4) Exclude: excludes entry from showing, rank, and prizes",
            ),
        ),
        migrations.AddField(
            model_name="medalexclusionrecord",
            name="exclusion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Include"),
                    (1, "Exclude Prize Only"),
                    (2, "Exclude And Show"),
                    (3, "Exclude And Show In Advanced"),
                    (4, "Exclude"),
                ],
                default=4,
                help_text="This sets the minimum exclusion status for this user.\n        </br>- (0) Include: shows entry & takes rank and prize.\n        </br>- (1) Exclude Prize and Show: shows entry, takes rank, but excludes from prizes\n        </br>- (2) Exclude and Show: shows entry, but excludes from rank and prizes\n        </br>- (3) Exclude and Show in Advanced: only shows entry in advanced views, excludes from rank and prizes\n        </br>- (4) Exclude: excludes entry from showing, rank, and prizes",
            ),
        ),
        migrations.RunPython(migrate, reverse_code=reverse_migrate),
    ]
