# Generated by Django 5.2.14 on 2026-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0021_remove_leaderboard_bot_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="finalize_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional. If not set, the Project's winners_announced_date will be used instead.\n        </br>- For all Leaderboards: used to filter out questions that have a resolution_set_time after this (as they were resolved after this Leaderboard was finalized).\n        </br>- Filtering MedalExclusionRecords: If set and end_time is not set, MedalExclusionRecords that have a start_time less than this (and no end_time or an end_time later that this Leaderboard's start_time) will be triggered.\n        ",
                null=True,
            ),
        ),
    ]
