# Generated by Django 5.2.15 on 2026-07-19 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from scoring.models import MINIMUM_REPUTATION
from utils.models import ModelBatchCreator


def migrate_year_performance(apps, schema_editor):
    # Populate "year_performance" reputation for each user from their score
    # on each finalized global 1-year peer leaderboard, using the
    # leaderboard's finalize_time as the reputation's time.
    Leaderboard = apps.get_model("scoring", "Leaderboard")
    LeaderboardEntry = apps.get_model("scoring", "LeaderboardEntry")
    Reputation = apps.get_model("scoring", "Reputation")

    leaderboards = Leaderboard.objects.filter(
        project__type="site_main",
        score_type__in=["peer_global", "peer_global_legacy"],
        finalized=True,
        finalize_time__isnull=False,
    )

    with ModelBatchCreator(model_class=Reputation, batch_size=1000) as creator:
        for leaderboard in leaderboards.iterator():
            if (
                leaderboard.start_time is None
                or leaderboard.end_time is None
                or leaderboard.end_time.year - leaderboard.start_time.year != 1
            ):
                continue

            entries = LeaderboardEntry.objects.filter(
                leaderboard=leaderboard, user__isnull=False
            )
            for entry in entries.iterator():
                creator.append(
                    Reputation(
                        user_id=entry.user_id,
                        time=leaderboard.finalize_time,
                        type="year_performance",
                        value=max(entry.score, MINIMUM_REPUTATION),
                    )
                )


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0021_remove_leaderboard_bot_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_at', models.DateTimeField(editable=False, null=True)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[('year_performance', 'Year Performance')], db_index=True, max_length=200)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_year_performance, migrations.RunPython.noop),
    ]
