# Generated by Django 5.2.15 on 2026-07-19 16:36

import math
from collections import defaultdict

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from scoring.models import MINIMUM_REPUTATION
from utils.models import ModelBatchCreator


def migrate_year_performance(apps, schema_editor):
    # Populate "year_performance" reputation for each user from their score
    # on each finalized global 1-year peer leaderboard, using the
    # leaderboard's finalize_time as the reputation's time.
    Leaderboard = apps.get_model("scoring", "Leaderboard")
    LeaderboardEntry = apps.get_model("scoring", "LeaderboardEntry")
    Reputation = apps.get_model("scoring", "Reputation")

    leaderboards = Leaderboard.objects.filter(
        project__type="site_main",
        score_type__in=["peer_global", "peer_global_legacy"],
        finalized=True,
        finalize_time__isnull=False,
    )

    with ModelBatchCreator(model_class=Reputation, batch_size=1000) as creator:
        for leaderboard in leaderboards.iterator():
            if (
                leaderboard.start_time is None
                or leaderboard.end_time is None
                or leaderboard.end_time.year - leaderboard.start_time.year != 1
            ):
                continue

            entries = LeaderboardEntry.objects.filter(
                leaderboard=leaderboard, user__isnull=False
            )
            for entry in entries.iterator():
                creator.append(
                    Reputation(
                        user_id=entry.user_id,
                        time=leaderboard.finalize_time,
                        type="year_performance",
                        value=max(entry.score, MINIMUM_REPUTATION),
                    )
                )


def migrate_average_peer_score(apps, schema_editor):
    # Populate "average_peer_score" reputation by replaying every user's peer
    # scores on public questions in chronological order, recording a snapshot
    # of their running reputation value after each update. This mirrors the
    # on-the-fly calculation PeerScoreReputationWeighted performs in
    # utils.the_math.aggregations (reputation_value / get_reputation_history).
    Score = apps.get_model("scoring", "Score")
    Reputation = apps.get_model("scoring", "Reputation")

    peer_scores = Score.objects.filter(
        score_type="peer",
        user__isnull=False,
        question__post__default_project__default_permission__isnull=False,
    ).order_by("edited_at")

    # user_id -> {question_id: (score, coverage)}, so a re-scored question
    # replaces its prior contribution instead of double-counting it.
    scores_by_user_question: dict[int, dict[int, tuple[float, float]]] = defaultdict(
        dict
    )
    # user_id -> [score_sum, coverage_sum]
    totals_by_user: dict[int, list[float]] = defaultdict(lambda: [0.0, 0.0])

    with ModelBatchCreator(model_class=Reputation, batch_size=1000) as creator:
        for score in peer_scores.iterator():
            totals = totals_by_user[score.user_id]
            previous = scores_by_user_question[score.user_id].get(score.question_id)
            if previous is not None:
                totals[0] -= previous[0]
                totals[1] -= previous[1]
            scores_by_user_question[score.user_id][score.question_id] = (
                score.score,
                score.coverage,
            )
            totals[0] += score.score
            totals[1] += score.coverage

            value = max(totals[0] / (30 + totals[1]), MINIMUM_REPUTATION)
            creator.append(
                Reputation(
                    user_id=score.user_id,
                    time=score.edited_at,
                    type="average_peer_score",
                    value=value,
                )
            )


def _softplus(x: float) -> float:
    # Numerically stable log(1 + exp(x)) - avoids overflow in exp(x) for
    # large positive x (used with x scaled by 1/MINIMUM_REPUTATION below,
    # so x routinely reaches magnitudes exp() can't handle directly).
    if x > 0:
        return x + math.log1p(math.exp(-x))
    return math.log1p(math.exp(x))


def migrate_derived_peer_reputations(apps, schema_editor):
    # Populate two reputation types derived from the same running (average
    # peer score r_i, total coverage c_i) state "average_peer_score" is
    # built from - both exist to address the same problem: about half of
    # users have negative average_peer_score, which (if used unadjusted)
    # shuts out a lot of the wisdom of the crowd, but new users need to be
    # excluded too, to prevent manipulation via freshly-created accounts.
    #
    # "peer_threshold_-20_coverage_50": a hard-thresholded r_i' with
    # rho=-20, gamma=50 -
    #   r_i' = MINIMUM_REPUTATION      if r_i < rho or c_i < gamma
    #   r_i' = r_i - rho               otherwise
    #
    # "peer_continuous_with_coverage": a smooth version of the same idea
    # (rho=0, gamma=50 - independent of the threshold version's rho above)
    # - shrinks r_i toward rho by a Bayesian-style blend weighted by c_i vs.
    # the coverage threshold gamma, then passes (blend - rho) through an
    # epsilon-scaled softplus, which smoothly approximates max(blend - rho,
    # 0) (exactly max() as MINIMUM_REPUTATION -> 0):
    #   blend = (gamma*rho + c_i*r_i) / (gamma + c_i)
    #   r_i' = MINIMUM_REPUTATION * softplus((blend - rho) / MINIMUM_REPUTATION)
    Score = apps.get_model("scoring", "Score")
    Reputation = apps.get_model("scoring", "Reputation")

    RHO_THRESHOLD = -20.0
    RHO_CONTINUOUS = 0.0
    GAMMA = 50.0

    peer_scores = Score.objects.filter(
        score_type="peer",
        user__isnull=False,
        question__post__default_project__default_permission__isnull=False,
    ).order_by("edited_at")

    # user_id -> {question_id: (score, coverage)}, so a re-scored question
    # replaces its prior contribution instead of double-counting it.
    scores_by_user_question: dict[int, dict[int, tuple[float, float]]] = defaultdict(
        dict
    )
    # user_id -> [score_sum, coverage_sum]
    totals_by_user: dict[int, list[float]] = defaultdict(lambda: [0.0, 0.0])

    with ModelBatchCreator(model_class=Reputation, batch_size=1000) as creator:
        for score in peer_scores.iterator():
            totals = totals_by_user[score.user_id]
            previous = scores_by_user_question[score.user_id].get(score.question_id)
            if previous is not None:
                totals[0] -= previous[0]
                totals[1] -= previous[1]
            scores_by_user_question[score.user_id][score.question_id] = (
                score.score,
                score.coverage,
            )
            totals[0] += score.score
            totals[1] += score.coverage

            r = totals[0] / (30 + totals[1])
            c = totals[1]

            if r < RHO_THRESHOLD or c < GAMMA:
                threshold_value = MINIMUM_REPUTATION
            else:
                threshold_value = max(r - RHO_THRESHOLD, MINIMUM_REPUTATION)

            blend = (GAMMA * RHO_CONTINUOUS + c * r) / (GAMMA + c)
            continuous_value = max(
                MINIMUM_REPUTATION
                * _softplus((blend - RHO_CONTINUOUS) / MINIMUM_REPUTATION),
                MINIMUM_REPUTATION,
            )

            creator.append(
                Reputation(
                    user_id=score.user_id,
                    time=score.edited_at,
                    type="peer_threshold_-20_coverage_50",
                    value=threshold_value,
                )
            )
            creator.append(
                Reputation(
                    user_id=score.user_id,
                    time=score.edited_at,
                    type="peer_continuous_with_coverage",
                    value=continuous_value,
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0021_remove_leaderboard_bot_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_at', models.DateTimeField(editable=False, null=True)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[('year_performance', 'Year Performance'), ('average_peer_score', 'Average Peer Score'), ('peer_threshold_-20_coverage_50', 'Peer Threshold Neg20 Coverage 50'), ('peer_continuous_with_coverage', 'Peer Continuous With Coverage')], db_index=True, max_length=200)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_year_performance, migrations.RunPython.noop),
        migrations.RunPython(migrate_average_peer_score, migrations.RunPython.noop),
        migrations.RunPython(migrate_derived_peer_reputations, migrations.RunPython.noop),
    ]
