# Generated by Django 5.2.17 on 2026-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0021_remove_leaderboard_bot_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="rank_ci_lower",
            field=models.IntegerField(
                blank=True, help_text="Rank Confidence Interval lower bound", null=True
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="rank_ci_upper",
            field=models.IntegerField(
                blank=True, help_text="Rank Confidence Interval upper bound", null=True
            ),
        ),
    ]
