# Generated by Django 5.0.6 on 2024-08-07 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ITNArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("title", models.CharField()),
                ("summary", models.CharField(null=True)),
                ("url", models.CharField()),
                ("publication", models.CharField()),
                ("img_url", models.CharField()),
                ("aid", models.BigIntegerField()),
                ("cluster_id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
