# Generated by Django 5.2.4 on 2025-07-18 14:08

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0028_forecast_end_time_after_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoherenceLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("edited_at", models.DateTimeField(editable=False, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        max_length=16,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "type",
                    models.CharField(choices=[("causal", "Causal")], max_length=16),
                ),
                (
                    "question1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coherence_links_as_q1",
                        to="questions.question",
                    ),
                ),
                (
                    "question2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coherence_links_as_q2",
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coherence_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        django.db.models.functions.comparison.Least(
                            "question1", "question2"
                        ),
                        django.db.models.functions.comparison.Greatest(
                            "question1", "question2"
                        ),
                        name="unique_user_question_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("question1", models.F("question2")), _negated=True
                        ),
                        name="different_questions",
                    ),
                ],
            },
        ),
    ]
