# Generated by Django 5.2.4 on 2025-07-14 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0028_forecast_end_time_after_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoherenceLink',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_at', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('p', 'Positive'), ('n', 'Negative')], max_length=1)),
                ('strength', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1)),
                ('type', models.CharField(choices=[('c', 'Causal')], max_length=1)),
                ('question1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coherence_links_as_q1', to='questions.question')),
                ('question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coherence_links_as_q2', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coherence_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
