# Generated by Django 5.2.4 on 2025-07-15 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coherence", "0001_initial"),
        ("questions", "0028_forecast_end_time_after_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coherencelink",
            constraint=models.UniqueConstraint(
                fields=("user", "question1", "question2"),
                name="unique_user_question_pair",
            ),
        ),
    ]
