# Generated by Django 5.1.10 on 2025-10-07 16:24

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


class Direction(models.TextChoices):
    POSITIVE = "positive"
    NEGATIVE = "negative"


class Strength(models.TextChoices):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


def convert_strength_to_number(strength: Strength) -> int:
    strength_map = {Strength.LOW: 1, Strength.MEDIUM: 2, Strength.HIGH: 5}
    return strength_map[strength]


def convert_direction_to_number(direction: Direction) -> int:
    direction_map = {
        Direction.POSITIVE: 1,
        Direction.NEGATIVE: -1,
    }
    return direction_map[direction]


def convert_direction_number_to_label(direction: int) -> Direction:
    direction_map = {1: Direction.POSITIVE, -1: Direction.NEGATIVE}
    return direction_map[int(direction)]


def convert_strength_number_to_label(strength: int) -> Strength:
    strength_map = {
        1: Strength.LOW,
        2: Strength.MEDIUM,
        3: Strength.MEDIUM,
        4: Strength.HIGH,
        5: Strength.HIGH,
    }
    return strength_map[int(strength)]


def modify_link_direction_strength(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    CoherenceLink = apps.get_model("coherence", "CoherenceLink")
    for link in CoherenceLink.objects.all():
        link.direction = convert_direction_to_number(link.direction)
        link.strength = convert_strength_to_number(link.strength)
        link.save(update_fields=["direction", "strength"])


def undo_modify_link_direction_strength(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    CoherenceLink = apps.get_model("coherence", "CoherenceLink")
    for link in CoherenceLink.objects.all():
        link.direction = convert_direction_number_to_label(link.direction)
        link.strength = convert_strength_number_to_label(link.strength)
        link.save(update_fields=["direction", "strength"])


class Migration(migrations.Migration):

    dependencies = [
        ("coherence", "0002_aggregatecoherencelink"),
    ]

    operations = [
        migrations.RunPython(
            modify_link_direction_strength,
            undo_modify_link_direction_strength,
        ),
        migrations.AlterField(
            model_name="coherencelink",
            name="direction",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="coherencelink",
            name="strength",
            field=models.IntegerField(default=0, editable=False),
        ),

    ]
