# Generated by Django 5.2.14 on 2026-07-14 11:45

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coherence', '0004_aggregatecoherencelinkvote'),
        ('questions', '0037_question_options_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoherenceLinkSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_at', models.DateTimeField(editable=False, null=True)),
                ('methods_by_candidate', models.JSONField(blank=True, default=dict)),
                ('paid_run_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='', max_length=16)),
                ('paid_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('paid_run_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('paid_run_methods_attempted', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('paid_run_methods_succeeded', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('paid_run_pool_hash', models.CharField(blank=True, default='', max_length=64)),
                ('paid_run_pool_size', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_run_elapsed_s', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_run_error_message', models.TextField(blank=True, default='')),
                ('free_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('target_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='questions.question')),
            ],
            options={
                'indexes': [models.Index(fields=['paid_run_started_at'], name='clsugg_paid_started_idx')],
            },
        ),
    ]
