export const MIDTERMS_COLORS = {
  demPrimary: "#6B7AE8",
  demLight: "#CECBF6",
  repPrimary: "#E8827A",
  repLight: "#FCCAC7",
  likelyD: "#4A5CD4",
  leanD: "#8B97EE",
  tossUp: "#D3D1C7",
  leanR: "#EDA8A4",
  likelyR: "#D4504A",
  // Matches the page body background (blue-200 in light mode) so uncontested
  // states recede into the page; contested states pop above them.
  notContested: "#eff4f4",
  notContestedDark: "#2f4155",
  stateStroke: "#ffffff",
  stateStrokeDark: "#22262b",
} as const;

export const STATE_NAMES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};
