# Generated by Django 5.0.6 on 2024-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
