name: Deploy the screenshot service

on:
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-24.04
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: metaculus-screenshot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and deploy to Heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku container:login # uses the HEROKU_API_KEY
          cd screenshot && ./deploy_to_heroku.sh
