name: Build and push a dev Docker image

on:
  workflow_dispatch:

jobs:
  deploy-a-dev-docker-image:
    runs-on: ubuntu-22.04
    environment: dev_env
    env:
      ENV_DOCKER_TAG: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to ghcr.io
        run: |
          docker build --platform linux/amd64 . -t ghcr.io/metaculus/metaculus:$ENV_DOCKER_TAG-$GITHUB_SHA -t ghcr.io/metaculus/metaculus:$ENV_DOCKER_TAG-latest --target all_runners --push
