name: Deploy the screenshots service

on:
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: metaculus-screenshot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and deploy to Heroku
        run: |
          heroku container:login # uses the HEROKU_API_KEY
          cd screenshots && ./deploy_to_heroku.sh
