name: Deploy storybook

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-24.04
    environment: prod_env
    defaults:
      run:
        working-directory: front_end
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front_end/package-lock.json
      - run: npm ci
      - run: npm run build-storybook
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./storybook-static --project-name=${{ secrets.CLOUDFLARE_PROJECT }} \
            --branch=${{ github.ref_name }}