from django.conf import settings
from django.contrib.auth import user_logged_in
from rest_framework.exceptions import ValidationError

from users.models import User


def create_user(strategy, details, backend, user=None, *args, **kwargs):
    """
    Replaces social_core's create_user step so we own social account creation.

    Also gates signup: a new account is only created when signups are enabled.
    Social-auth usernames are autogenerated, so accounts are created with
    username_set_at=None (no human-set stamp) - the manager would otherwise
    default it to now. This is also the seam for a custom username generator.
    """
    if user:
        return {"is_new": False}

    if not settings.PUBLIC_ALLOW_SIGNUP:
        raise ValidationError("Signup is disabled")

    fields = {
        name: kwargs.get(name, details.get(name)) for name in ["email", "username"]
    }
    if not fields:
        return None

    email = fields.get("email")
    username = fields.get("username")

    user = User.objects.create_user(
        # TODO: will be switched to the autogenerated usernames in the future,
        #  so we could deprecate `social_core.pipeline.user.get_username`
        username=username,
        email=email,
        username_set_at=None,
    )

    return {
        "is_new": True,
        "user": user,
    }


def send_user_logged_in(strategy, user=None, *args, **kwargs):
    """
    Sends the user_logged_in signal when a user logs in via social auth.
    """
    if user:
        user_logged_in.send(sender=user.__class__, request=strategy.request, user=user)

    return {"user": user, **kwargs}
